// Generated by Formal AI's Rust-owned substitution compiler.
#![no_std]

extern crate alloc;

use alloc::borrow::ToOwned as _;
use alloc::collections::{BTreeMap, BTreeSet};
use alloc::format;
use alloc::string::String;
use core::alloc::{GlobalAlloc, Layout};
use core::cell::UnsafeCell;
use core::fmt::Write as _;
use core::sync::atomic::{AtomicUsize, Ordering};

const INPUT_CAPACITY: usize = 65_536;
const OUTPUT_CAPACITY: usize = 65_536;
const HEAP_CAPACITY: usize = 2_097_152;

static mut INPUT: [u8; INPUT_CAPACITY] = [0; INPUT_CAPACITY];
static mut OUTPUT: [u8; OUTPUT_CAPACITY] = [0; OUTPUT_CAPACITY];

struct Heap { buffer: UnsafeCell<[u8; HEAP_CAPACITY]> }
unsafe impl Sync for Heap {}
static HEAP: Heap = Heap { buffer: UnsafeCell::new([0; HEAP_CAPACITY]) };
static OFFSET: AtomicUsize = AtomicUsize::new(0);
struct Allocator;

unsafe impl GlobalAlloc for Allocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let base = HEAP.buffer.get() as usize;
        loop {
            let current = OFFSET.load(Ordering::Relaxed);
            let address = (base + current + layout.align() - 1) & !(layout.align() - 1);
            let next = address - base + layout.size();
            if next > HEAP_CAPACITY { return core::ptr::null_mut(); }
            if OFFSET.compare_exchange(current, next, Ordering::AcqRel, Ordering::Relaxed).is_ok() {
                return address as *mut u8;
            }
        }
    }
    unsafe fn dealloc(&self, _pointer: *mut u8, _layout: Layout) {}
}

#[global_allocator]
static ALLOCATOR: Allocator = Allocator;

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo<'_>) -> ! { loop {} }

const MAX_APPLICATIONS: usize = 64;

#[allow(dead_code)]
#[derive(Clone, Copy)]
enum Node {
    Literal(&'static str),
    Variable(&'static str),
    PrefixVariable(&'static str, &'static str),
}

#[derive(Clone, Copy)]
struct Pattern {
    from: Node,
    to: Node,
}

struct Action {
    remove: Pattern,
    add: &'static [Pattern],
}

struct Rule {
    conditions: &'static [Pattern],
    actions: &'static [Action],
}

type Link = (String, String);
type Bindings = BTreeMap<String, String>;

fn bind(bindings: &mut Bindings, name: &str, value: &str) -> bool {
    if let Some(bound) = bindings.get(name) {
        bound == value
    } else {
        bindings.insert(name.to_owned(), value.to_owned());
        true
    }
}

fn match_node(pattern: Node, value: &str, bindings: &mut Bindings) -> bool {
    match pattern {
        Node::Literal(literal) => literal == value,
        Node::Variable(name) => bind(bindings, name, value),
        Node::PrefixVariable(prefix, name) => value
            .strip_prefix(prefix)
            .is_some_and(|suffix| bind(bindings, name, suffix)),
    }
}

fn match_pattern(pattern: Pattern, link: &Link, bindings: &mut Bindings) -> bool {
    match_node(pattern.from, &link.0, bindings)
        && match_node(pattern.to, &link.1, bindings)
}

fn find_bindings(
    patterns: &[Pattern],
    links: &BTreeSet<Link>,
    bindings: Bindings,
) -> Option<Bindings> {
    let Some((pattern, remaining)) = patterns.split_first() else {
        return Some(bindings);
    };
    for link in links {
        let mut candidate = bindings.clone();
        if match_pattern(*pattern, link, &mut candidate) {
            if let Some(found) = find_bindings(remaining, links, candidate) {
                return Some(found);
            }
        }
    }
    None
}

fn instantiate_node(node: Node, bindings: &Bindings) -> Option<String> {
    match node {
        Node::Literal(value) => Some(value.to_owned()),
        Node::Variable(name) => bindings.get(name).cloned(),
        Node::PrefixVariable(prefix, name) => bindings.get(name).map(|value| format!("{prefix}{value}")),
    }
}

fn instantiate(pattern: Pattern, bindings: &Bindings) -> Option<Link> {
    Some((
        instantiate_node(pattern.from, bindings)?,
        instantiate_node(pattern.to, bindings)?,
    ))
}

fn apply_rule(rule: &Rule, links: &mut BTreeSet<Link>) -> bool {
    let mut required = rule.conditions.to_vec();
    required.extend(rule.actions.iter().map(|action| action.remove));
    let Some(bindings) = find_bindings(&required, links, Bindings::new()) else {
        return false;
    };
    let before = links.clone();
    for action in rule.actions {
        let Some(remove) = instantiate(action.remove, &bindings) else {
            return false;
        };
        links.remove(&remove);
        for add in action.add {
            let Some(link) = instantiate(*add, &bindings) else {
                return false;
            };
            links.insert(link);
        }
    }
    *links != before
}

fn transform(input: &str) -> String {
    let mut links: BTreeSet<Link> = input
        .lines()
        .filter_map(|line| line.split_once('\t'))
        .map(|(from, to)| (from.to_owned(), to.to_owned()))
        .collect();
    for _ in 0..MAX_APPLICATIONS {
        let Some(rule) = RULES.iter().find(|rule| apply_rule(rule, &mut links)) else {
            break;
        };
        let _ = rule;
    }
    let mut output = String::new();
    for (from, to) in links {
        let _ = writeln!(output, "{from}\t{to}");
    }
    output
}
static RULES: &[Rule] = &[
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("path_argument") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg") },
        ] },
    ] },
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("path_argument") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_reverse_sort") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg_reverse_sort") },
        ] },
    ] },
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("cancel_reverse_sort") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_reverse_sort") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files") },
        ] },
    ] },
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("cancel_reverse_sort") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg_reverse_sort") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg") },
        ] },
    ] },
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("reverse_sort") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_reverse_sort") },
        ] },
    ] },
    Rule { conditions: &[
        Pattern { from: Node::Literal("request:modifier"), to: Node::Literal("reverse_sort") },
    ], actions: &[
        Action { remove: Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg") }, add: &[
            Pattern { from: Node::Literal("request:task"), to: Node::Literal("list_files_arg_reverse_sort") },
        ] },
    ] },
];

#[no_mangle]
pub extern "C" fn input_ptr() -> *mut u8 { core::ptr::addr_of_mut!(INPUT).cast::<u8>() }

#[no_mangle]
pub extern "C" fn output_ptr() -> *mut u8 { core::ptr::addr_of_mut!(OUTPUT).cast::<u8>() }

#[no_mangle]
pub extern "C" fn input_capacity() -> usize { INPUT_CAPACITY }

#[no_mangle]
pub extern "C" fn run(length: usize) -> usize {
    OFFSET.store(0, Ordering::Release);
    let length = length.min(INPUT_CAPACITY);
    let bytes = unsafe { core::slice::from_raw_parts(core::ptr::addr_of!(INPUT).cast::<u8>(), length) };
    let Ok(input) = core::str::from_utf8(bytes) else { return 0; };
    let output = transform(input);
    let length = output.len().min(OUTPUT_CAPACITY);
    unsafe {
        core::ptr::copy_nonoverlapping(output.as_ptr(), core::ptr::addr_of_mut!(OUTPUT).cast::<u8>(), length);
    }
    length
}
