//! Compile-time enumeration of legacy seeded API-response `.lino` files.
//!
//! Issue #398 removed the committed legacy bundle in favor of explicit
//! source snapshots under `data/cache/wikidata/`. The reader remains so older
//! or locally generated `data/seed/api-cache/` bundles can still be replayed.
//! When that directory is absent this script emits an empty registry.
//!
//! `include_str!` cannot iterate a directory, so this build script writes
//! a generated `seed_bundle_files.rs` into `OUT_DIR` that lists every
//! legacy seed file in deterministic order. `cache.rs` includes that file via
//! `include!(concat!(env!("OUT_DIR"), "/seed_bundle_files.rs"))` so all
//! parts ship in the binary without per-file edits when the legacy bundle is
//! present.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let seed_dir = manifest_dir.join("data/seed/api-cache");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("seed_bundle_files.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", seed_dir.display());

    let mut files = enumerate_lino_files(&seed_dir);
    files.sort_by_key(|a| seed_sort_key(a));

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs — do not edit.\n");
    generated.push_str("pub const SEED_BUNDLE_FILES: &[(&str, &str)] = &[\n");
    for path in &files {
        let rel = path
            .strip_prefix(&manifest_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        let abs = path.to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={abs}");
        generated.push_str("    (\"");
        generated.push_str(&rel);
        generated.push_str("\", include_str!(\"");
        generated.push_str(&abs);
        generated.push_str("\")),\n");
    }
    generated.push_str("];\n");

    fs::write(&out_path, generated).expect("write seed_bundle_files.rs");

    emit_owned_source_manifest(&manifest_dir, &out_dir);
}

/// Emit `owned_source_files.rs` — the compile-time manifest of every owned Rust
/// source file under `src/`, embedded via `include_str!`.
///
/// Issue #558 asks for *"the entire source code of our system"* to be translatable
/// to the links/meta language and *"present in the seed data"*. `include_str!`
/// cannot iterate a directory, so this script writes a generated slice of
/// `(repo_relative_path, source_text)` pairs into `OUT_DIR`; the whole-repository
/// projection ([`crate::self_source_graph`]) includes it via
/// `include!(concat!(env!("OUT_DIR"), "/owned_source_files.rs"))` so every module's
/// source ships in the binary and the projection works with no filesystem access —
/// exactly as it must when the loop runs from an agent CLI's sandbox workdir.
fn emit_owned_source_manifest(manifest_dir: &Path, out_dir: &Path) {
    let src_dir = manifest_dir.join("src");
    let out_path = out_dir.join("owned_source_files.rs");
    println!("cargo:rerun-if-changed={}", src_dir.display());

    let mut files = Vec::new();
    enumerate_rust_files(&src_dir, &mut files);
    // Deterministic order: sort by the path *string* (not component-wise like
    // `PathBuf`'s `Ord`, which would order `memory/bundle.rs` before `memory.rs`)
    // so the manifest — and every projection derived from it — is stable across
    // machines and rebuilds and matches conventional lexicographic path order.
    files.sort_by(|a, b| a.to_string_lossy().cmp(&b.to_string_lossy()));

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs — do not edit.\n");
    generated.push_str("pub const OWNED_SOURCE_FILES: &[(&str, &str)] = &[\n");
    for path in &files {
        let rel = path
            .strip_prefix(manifest_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        let abs = path.to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={abs}");
        generated.push_str("    (\"");
        generated.push_str(&rel);
        generated.push_str("\", include_str!(\"");
        generated.push_str(&abs);
        generated.push_str("\")),\n");
    }
    generated.push_str("];\n");

    fs::write(&out_path, generated).expect("write owned_source_files.rs");
}

/// Recursively collect every `.rs` file under `dir` in filesystem order.
fn enumerate_rust_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            enumerate_rust_files(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

fn enumerate_lino_files(seed_dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(seed_dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some("lino") {
            out.push(path);
        }
    }
    out
}

// Keeps split records in body order: `<bucket>.lino` is chunk 0 and must
// load before `<bucket>-part1.lino`, `<bucket>-part2.lino`, ... in
// numeric order. Lexicographic sort puts `<bucket>-part10.lino` before
// `<bucket>-part2.lino` and `<bucket>.lino` after every part, both of
// which reorder the base64 chunks and corrupt the assembled body.
fn seed_sort_key(path: &Path) -> (String, u32, String) {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default();
    if let Some((bucket, suffix)) = stem.rsplit_once("-part") {
        if let Ok(n) = suffix.parse::<u32>() {
            return (bucket.to_string(), n, stem.to_string());
        }
    }
    (stem.to_string(), 0, stem.to_string())
}
