//! Compile-time enumeration of seeded API-response `.lino` files.
//!
//! The seed bundle under `data/seed/api-cache/` may grow to multiple
//! `<bucket>-partN.lino` files (issue #221 caps each at 1500 lines).
//! `include_str!` cannot iterate a directory, so this build script writes
//! a generated `seed_bundle_files.rs` into `OUT_DIR` that lists every
//! seed file in deterministic order. `cache.rs` includes that file via
//! `include!(concat!(env!("OUT_DIR"), "/seed_bundle_files.rs"))` so all
//! parts ship in the binary without per-file edits.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let seed_dir = manifest_dir.join("data/seed/api-cache");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("seed_bundle_files.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", seed_dir.display());

    let mut files = enumerate_lino_files(&seed_dir);
    files.sort_by_key(|a| seed_sort_key(a));

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs — do not edit.\n");
    generated.push_str("pub const SEED_BUNDLE_FILES: &[(&str, &str)] = &[\n");
    for path in &files {
        let rel = path
            .strip_prefix(&manifest_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        let abs = path.to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={abs}");
        generated.push_str("    (\"");
        generated.push_str(&rel);
        generated.push_str("\", include_str!(\"");
        generated.push_str(&abs);
        generated.push_str("\")),\n");
    }
    generated.push_str("];\n");

    fs::write(&out_path, generated).expect("write seed_bundle_files.rs");
}

fn enumerate_lino_files(seed_dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(seed_dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some("lino") {
            out.push(path);
        }
    }
    out
}

// Keeps split records in body order: `<bucket>.lino` is chunk 0 and must
// load before `<bucket>-part1.lino`, `<bucket>-part2.lino`, ... in
// numeric order. Lexicographic sort puts `<bucket>-part10.lino` before
// `<bucket>-part2.lino` and `<bucket>.lino` after every part, both of
// which reorder the base64 chunks and corrupt the assembled body.
fn seed_sort_key(path: &Path) -> (String, u32, String) {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default();
    if let Some((bucket, suffix)) = stem.rsplit_once("-part") {
        if let Ok(n) = suffix.parse::<u32>() {
            return (bucket.to_string(), n, stem.to_string());
        }
    }
    (stem.to_string(), 0, stem.to_string())
}
