// Embedded Links Notation seed files and the file registry.
//
// Generated by `rust-script scripts/generate-seed-registry.rs --write` from
// `data/meta/seed-registry.lino`. Do not edit by hand: issue #991 moved this
// inventory out of hand-written lists because two branches adding a seed file
// always appended to the same lines here, and the registry is `merge=union` so
// that never happens again.
//
// `src/seed/embedded.rs` pulls this in with `include!`, which keeps it outside
// rustfmt's reach -- the generator owns every byte, so a regenerated file is
// byte-identical whatever rustfmt would have preferred.

/// Raw embedded contents (used by `merged_bundle` and by tests).
pub const AGENT_INFO_LINO: &str = include_str!("../../../data/seed/agent-info.lino");
pub const AGENTIC_TOOL_CAPABILITIES_LINO: &str =
    include_str!("../../../data/seed/agentic-tool-capabilities.lino");
pub const APPROVED_LESSONS_LINO: &str = include_str!("../../../data/seed/approved-lessons.lino");
pub const BRAINSTORM_SEEDS_LINO: &str = include_str!("../../../data/seed/brainstorm-seeds.lino");
pub const CALLER_CONTEXT_LINO: &str = include_str!("../../../data/seed/caller-context.lino");
pub const CLIENT_COMPLETION_CONTRACTS_LINO: &str =
    include_str!("../../../data/seed/client-completion-contracts.lino");
pub const CLIENT_INTEGRATIONS_LINO: &str =
    include_str!("../../../data/seed/client-integrations.lino");
pub const CODING_GUIDANCE_LINO: &str = include_str!("../../../data/seed/coding-guidance.lino");
pub const CODING_IDIOMS_LINO: &str = include_str!("../../../data/seed/coding-idioms.lino");
pub const COMMAND_OUTCOME_LINO: &str = include_str!("../../../data/seed/command-outcome.lino");
pub const COMPUTER_USE_TASKS_LINO: &str =
    include_str!("../../../data/seed/computer-use-tasks.lino");
pub const CONCEPT_CONTEXTS_LINO: &str = include_str!("../../../data/seed/concept-contexts.lino");
pub const CONCEPTS_LINO: &str = include_str!("../../../data/seed/concepts.lino");
pub const CONTRIBUTION_ARTIFACTS_LINO: &str =
    include_str!("../../../data/seed/contribution-artifacts.lino");
pub const COREFERENCE_LINO: &str = include_str!("../../../data/seed/coreference.lino");
pub const DEMO_DIALOGS_LINO: &str = include_str!("../../../data/seed/demo-dialogs.lino");
pub const DRAFT_STRATEGIES_LINO: &str = include_str!("../../../data/seed/draft-strategies.lino");
pub const ENTITY_NAMES_LINO: &str = include_str!("../../../data/seed/entity-names.lino");
pub const ENVIRONMENTS_LINO: &str = include_str!("../../../data/seed/environments.lino");
pub const FACTS_LINO: &str = include_str!("../../../data/seed/facts.lino");
pub const FORMAL_LANGUAGE_PROJECTIONS_LINO: &str =
    include_str!("../../../data/seed/formal-language-projections.lino");
pub const FORMALIZATION_RELATIONS_LINO: &str =
    include_str!("../../../data/seed/formalization-relations.lino");
pub const GREETINGS_LINO: &str = include_str!("../../../data/seed/greetings.lino");
pub const HANDLER_FAMILY_METHODS_LINO: &str =
    include_str!("../../../data/seed/handler-family-methods.lino");
pub const HANDLER_PRECEDENCE_LINO: &str =
    include_str!("../../../data/seed/handler-precedence.lino");
pub const HANDLER_PROMOTIONS_LINO: &str =
    include_str!("../../../data/seed/handler-promotions.lino");
pub const HANDLER_RULES_LINO: &str = include_str!("../../../data/seed/handler-rules.lino");
pub const HELLO_WORLD_PROGRAMS_LINO: &str =
    include_str!("../../../data/seed/hello-world-programs.lino");
pub const IDENTITY_LINO: &str = include_str!("../../../data/seed/identity.lino");
pub const INTENT_ROUTING_LINO: &str = include_str!("../../../data/seed/intent-routing.lino");
pub const INTERFACE_CAPABILITIES_LINO: &str =
    include_str!("../../../data/seed/interface-capabilities.lino");
pub const LANGUAGE_DETECTION_LINO: &str =
    include_str!("../../../data/seed/language-detection.lino");
pub const LANGUAGES_LINO: &str = include_str!("../../../data/seed/languages.lino");
pub const LEARNED_METHODS_LINO: &str = include_str!("../../../data/seed/learned-methods.lino");
pub const LEARNED_PROGRAM_RULES_LINO: &str =
    include_str!("../../../data/seed/learned-program-rules.lino");
pub const LEARNED_REQUEST_OPENERS_LINO: &str =
    include_str!("../../../data/seed/learned-request-openers.lino");
pub const LEARNING_SOURCES_LINO: &str = include_str!("../../../data/seed/learning-sources.lino");
pub const MARKET_PRICE_REFERENCES_LINO: &str =
    include_str!("../../../data/seed/market-price-references.lino");
pub const MEANINGS_LINO: &str = include_str!("../../../data/seed/meanings.lino");
pub const MEANINGS_ACTS_LINO: &str = include_str!("../../../data/seed/meanings-acts.lino");
pub const MEANINGS_AGENT_ACTIONS_LINO: &str =
    include_str!("../../../data/seed/meanings-agent-actions.lino");
pub const MEANINGS_BEHAVIOR_RULES_LINO: &str =
    include_str!("../../../data/seed/meanings-behavior-rules.lino");
pub const MEANINGS_CALCULATOR_LINO: &str =
    include_str!("../../../data/seed/meanings-calculator.lino");
pub const MEANINGS_CALENDAR_LINO: &str = include_str!("../../../data/seed/meanings-calendar.lino");
pub const MEANINGS_CODING_CATALOG_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-catalog.lino");
pub const MEANINGS_CODING_CONFIG_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-config.lino");
pub const MEANINGS_CODING_REQUEST_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-request.lino");
pub const MEANINGS_CODING_STRUCTURE_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-structure.lino");
pub const MEANINGS_CODING_STRUCTURE_2_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-structure-2.lino");
pub const MEANINGS_CODING_TASKS_LINO: &str =
    include_str!("../../../data/seed/meanings-coding-tasks.lino");
pub const MEANINGS_COMPUTER_USE_LINO: &str =
    include_str!("../../../data/seed/meanings-computer-use.lino");
pub const MEANINGS_CONCEPT_LOOKUP_LINO: &str =
    include_str!("../../../data/seed/meanings-concept-lookup.lino");
pub const MEANINGS_CONVERSATION_LINO: &str =
    include_str!("../../../data/seed/meanings-conversation.lino");
pub const MEANINGS_DECOMPOSITION_LINO: &str =
    include_str!("../../../data/seed/meanings-decomposition.lino");
pub const MEANINGS_DEFINITION_MERGE_LINO: &str =
    include_str!("../../../data/seed/meanings-definition-merge.lino");
pub const MEANINGS_DOCS_LINO: &str = include_str!("../../../data/seed/meanings-docs.lino");
pub const MEANINGS_FACTS_LINO: &str = include_str!("../../../data/seed/meanings-facts.lino");
pub const MEANINGS_FEATURE_CAPABILITY_LINO: &str =
    include_str!("../../../data/seed/meanings-feature-capability.lino");
pub const MEANINGS_FILE_EDIT_LINO: &str =
    include_str!("../../../data/seed/meanings-file-edit.lino");
pub const MEANINGS_FILE_WRITE_LINO: &str =
    include_str!("../../../data/seed/meanings-file-write.lino");
pub const MEANINGS_FINANCE_LINO: &str = include_str!("../../../data/seed/meanings-finance.lino");
pub const MEANINGS_FORMALIZATION_NEEDS_LINO: &str =
    include_str!("../../../data/seed/meanings-formalization-needs.lino");
pub const MEANINGS_FORMALIZATION_RELATIONS_LINO: &str =
    include_str!("../../../data/seed/meanings-formalization-relations.lino");
pub const MEANINGS_FORMALIZATION_REPORT_LINO: &str =
    include_str!("../../../data/seed/meanings-formalization-report.lino");
pub const MEANINGS_HOW_LINO: &str = include_str!("../../../data/seed/meanings-how.lino");
pub const MEANINGS_INTENT_LINO: &str = include_str!("../../../data/seed/meanings-intent.lino");
pub const MEANINGS_LEXICAL_META_LINO: &str =
    include_str!("../../../data/seed/meanings-lexical-meta.lino");
pub const MEANINGS_LEXICON_IMPORT_01_LINO: &str =
    include_str!("../../../data/seed/meanings-lexicon-import-01.lino");
pub const MEANINGS_LEXICON_IMPORT_02_LINO: &str =
    include_str!("../../../data/seed/meanings-lexicon-import-02.lino");
pub const MEANINGS_LEXICON_IMPORT_03_LINO: &str =
    include_str!("../../../data/seed/meanings-lexicon-import-03.lino");
pub const MEANINGS_LEXICON_IMPORT_04_LINO: &str =
    include_str!("../../../data/seed/meanings-lexicon-import-04.lino");
pub const MEANINGS_LINKS_ROOT_LINO: &str =
    include_str!("../../../data/seed/meanings-links-root.lino");
pub const MEANINGS_LOCAL_SEARCH_LINO: &str =
    include_str!("../../../data/seed/meanings-local-search.lino");
pub const MEANINGS_MEMBERSHIP_LINO: &str =
    include_str!("../../../data/seed/meanings-membership.lino");
pub const MEANINGS_META_LINO: &str = include_str!("../../../data/seed/meanings-meta.lino");
pub const MEANINGS_NOTE_COMPOSITION_LINO: &str =
    include_str!("../../../data/seed/meanings-note-composition.lino");
pub const MEANINGS_NUMBER_CONSTRAINTS_LINO: &str =
    include_str!("../../../data/seed/meanings-number-constraints.lino");
pub const MEANINGS_OBJECT_SHAPES_LINO: &str =
    include_str!("../../../data/seed/meanings-object-shapes.lino");
pub const MEANINGS_ONTOLOGY_LINO: &str = include_str!("../../../data/seed/meanings-ontology.lino");
pub const MEANINGS_PLAYWRIGHT_LINO: &str =
    include_str!("../../../data/seed/meanings-playwright.lino");
pub const MEANINGS_POLICY_LINO: &str = include_str!("../../../data/seed/meanings-policy.lino");
pub const MEANINGS_PROGRAM_SYNTHESIS_LINO: &str =
    include_str!("../../../data/seed/meanings-program-synthesis.lino");
pub const MEANINGS_PROOF_LINO: &str = include_str!("../../../data/seed/meanings-proof.lino");
pub const MEANINGS_REPOSITORY_WORKFLOW_LINO: &str =
    include_str!("../../../data/seed/meanings-repository-workflow.lino");
pub const MEANINGS_RESEARCH_TABLE_LINO: &str =
    include_str!("../../../data/seed/meanings-research-table.lino");
pub const MEANINGS_ROUTING_VOCABULARY_LINO: &str =
    include_str!("../../../data/seed/meanings-routing-vocabulary.lino");
pub const MEANINGS_SEARCH_LINO: &str = include_str!("../../../data/seed/meanings-search.lino");
pub const MEANINGS_SELECTION_CRITERIA_LINO: &str =
    include_str!("../../../data/seed/meanings-selection-criteria.lino");
pub const MEANINGS_SEMANTIC_META_LINO: &str =
    include_str!("../../../data/seed/meanings-semantic-meta.lino");
pub const MEANINGS_SKILL_COMPILER_LINO: &str =
    include_str!("../../../data/seed/meanings-skill-compiler.lino");
pub const MEANINGS_SKILL_PROCEDURE_LINO: &str =
    include_str!("../../../data/seed/meanings-skill-procedure.lino");
pub const MEANINGS_SOFTWARE_PROJECT_LINO: &str =
    include_str!("../../../data/seed/meanings-software-project.lino");
pub const MEANINGS_STATEMENT_MERGE_LINO: &str =
    include_str!("../../../data/seed/meanings-statement-merge.lino");
pub const MEANINGS_SUBSTITUTION_COMPILER_LINO: &str =
    include_str!("../../../data/seed/meanings-substitution-compiler.lino");
pub const MEANINGS_SUMMARY_LINO: &str = include_str!("../../../data/seed/meanings-summary.lino");
pub const MEANINGS_TOOL_ACCESS_LINO: &str =
    include_str!("../../../data/seed/meanings-tool-access.lino");
pub const MEANINGS_TRANSLATE_CYCLE_LINO: &str =
    include_str!("../../../data/seed/meanings-translate-cycle.lino");
pub const MEANINGS_TRANSLATION_LINO: &str =
    include_str!("../../../data/seed/meanings-translation.lino");
pub const MEANINGS_UNITS_LINO: &str = include_str!("../../../data/seed/meanings-units.lino");
pub const MEANINGS_VERIFIABLE_TASK_LINO: &str =
    include_str!("../../../data/seed/meanings-verifiable-task.lino");
pub const MEANINGS_WEB_FOLLOWUP_LINO: &str =
    include_str!("../../../data/seed/meanings-web-followup.lino");
pub const MEANINGS_WEB_NAVIGATION_LINO: &str =
    include_str!("../../../data/seed/meanings-web-navigation.lino");
pub const MEANINGS_WEB_RESEARCH_LINO: &str =
    include_str!("../../../data/seed/meanings-web-research.lino");
pub const MEANINGS_WEB_SEARCH_LINO: &str =
    include_str!("../../../data/seed/meanings-web-search.lino");
pub const MEANINGS_WEB_SEARCH_QUERY_LINO: &str =
    include_str!("../../../data/seed/meanings-web-search-query.lino");
pub const MEANINGS_WIKIDATA_LINO: &str = include_str!("../../../data/seed/meanings-wikidata.lino");
pub const MEANINGS_WRITING_SYSTEMS_LINO: &str =
    include_str!("../../../data/seed/meanings-writing-systems.lino");
pub const MEMORY_PROGRAMS_LINO: &str = include_str!("../../../data/seed/memory-programs.lino");
pub const METHOD_EXECUTION_LINO: &str = include_str!("../../../data/seed/method-execution.lino");
pub const MODEL_ALIASES_LINO: &str = include_str!("../../../data/seed/model-aliases.lino");
pub const MULTILINGUAL_RESPONSES_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses.lino");
pub const MULTILINGUAL_RESPONSES_AGENTIC_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-agentic.lino");
pub const MULTILINGUAL_RESPONSES_AGENTIC_CONTINUATION_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-agentic-continuation.lino");
pub const MULTILINGUAL_RESPONSES_AGENTIC_TOOLS_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-agentic-tools.lino");
pub const MULTILINGUAL_RESPONSES_CLIENT_CONFIG_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-client-config.lino");
pub const MULTILINGUAL_RESPONSES_CONCEPT_LOOKUP_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-concept-lookup.lino");
pub const MULTILINGUAL_RESPONSES_DECOMPOSITION_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-decomposition.lino");
pub const MULTILINGUAL_RESPONSES_ENTITIES_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-entities.lino");
pub const MULTILINGUAL_RESPONSES_EXTERNAL_BENCHMARK_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-external-benchmark.lino");
pub const MULTILINGUAL_RESPONSES_ISSUE_710_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-issue-710.lino");
pub const MULTILINGUAL_RESPONSES_LANGUAGE_PROTOCOL_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-language-protocol.lino");
pub const MULTILINGUAL_RESPONSES_MEMORY_PROGRAM_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-memory-program.lino");
pub const MULTILINGUAL_RESPONSES_ORCHESTRATION_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-orchestration.lino");
pub const MULTILINGUAL_RESPONSES_PARITY_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-parity.lino");
pub const MULTILINGUAL_RESPONSES_PATTERN_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-pattern.lino");
pub const MULTILINGUAL_RESPONSES_POLICY_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-policy.lino");
pub const MULTILINGUAL_RESPONSES_PROCEDURE_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-procedure.lino");
pub const MULTILINGUAL_RESPONSES_SUBSTITUTION_COMPILER_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-substitution-compiler.lino");
pub const MULTILINGUAL_RESPONSES_SUMMARIZATION_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-summarization.lino");
pub const MULTILINGUAL_RESPONSES_SUMMARIZATION_QUALITY_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-summarization-quality.lino");
pub const MULTILINGUAL_RESPONSES_SYMBOLIC_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-symbolic.lino");
pub const MULTILINGUAL_RESPONSES_SYNTHESIS_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-synthesis.lino");
pub const MULTILINGUAL_RESPONSES_THINKING_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-thinking.lino");
pub const MULTILINGUAL_RESPONSES_THINKING_NARRATIVE_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-thinking-narrative.lino");
pub const MULTILINGUAL_RESPONSES_TRANSLATE_LINO: &str =
    include_str!("../../../data/seed/multilingual-responses-translate.lino");
pub const NUMERIC_LIST_OPERATIONS_LINO: &str =
    include_str!("../../../data/seed/numeric-list-operations.lino");
pub const OBLIGATION_MISMATCH_LINO: &str =
    include_str!("../../../data/seed/obligation-mismatch.lino");
pub const OPERATION_VOCABULARY_LINO: &str =
    include_str!("../../../data/seed/operation-vocabulary.lino");
pub const PERSONAS_LINO: &str = include_str!("../../../data/seed/personas.lino");
pub const PLANNER_PRECEDENCE_LINO: &str =
    include_str!("../../../data/seed/planner-precedence.lino");
pub const PROGRAM_CST_GRAMMARS_LINO: &str =
    include_str!("../../../data/seed/program-cst-grammars.lino");
pub const PROGRAM_PLAN_RULES_LINO: &str =
    include_str!("../../../data/seed/program-plan-rules.lino");
pub const PROJECTS_LINO: &str = include_str!("../../../data/seed/projects.lino");
pub const PROMPT_PATTERNS_LINO: &str = include_str!("../../../data/seed/prompt-patterns.lino");
pub const PROOF_PROGRAM_TEMPLATES_LINO: &str =
    include_str!("../../../data/seed/proof-program-templates.lino");
pub const QUESTION_NECESSITY_LINO: &str =
    include_str!("../../../data/seed/question-necessity.lino");
pub const RELEASE_TIMELINES_LINO: &str = include_str!("../../../data/seed/release-timelines.lino");
pub const REPOSITORY_COMMAND_ALLOWLIST_LINO: &str =
    include_str!("../../../data/seed/repository-command-allowlist.lino");
pub const RESEARCH_TABLE_PROCEDURE_LINO: &str =
    include_str!("../../../data/seed/research-table-procedure.lino");
pub const SELF_IMPROVEMENT_LOOP_LINO: &str =
    include_str!("../../../data/seed/self-improvement-loop.lino");
pub const SENTENCE_PUNCTUATION_LINO: &str =
    include_str!("../../../data/seed/sentence-punctuation.lino");
pub const SETUP_PUBLISHERS_LINO: &str = include_str!("../../../data/seed/setup-publishers.lino");
pub const SHELL_INTENTS_LINO: &str = include_str!("../../../data/seed/shell-intents.lino");
pub const SOURCES_REGISTRY_LINO: &str = include_str!("../../../data/seed/sources-registry.lino");
pub const SUMMARY_TOPICS_LINO: &str = include_str!("../../../data/seed/summary-topics.lino");
pub const TERMINAL_COMMANDS_LINO: &str = include_str!("../../../data/seed/terminal-commands.lino");
pub const TOOL_RESOURCE_SCOPES_LINO: &str =
    include_str!("../../../data/seed/tool-resource-scopes.lino");
pub const TOOLCHAINS_LINO: &str = include_str!("../../../data/seed/toolchains.lino");
pub const TOOLS_LINO: &str = include_str!("../../../data/seed/tools.lino");
pub const TRIZ_PRINCIPLES_LINO: &str = include_str!("../../../data/seed/triz-principles.lino");

/// Embedded copy of every Links Notation seed file. Returned in registry
/// order so callers can render the merged bundle deterministically.
#[must_use]
pub fn seed_files() -> Vec<(&'static str, &'static str)> {
    vec![
        ("data/seed/agent-info.lino", AGENT_INFO_LINO),
        ("data/seed/agentic-tool-capabilities.lino", AGENTIC_TOOL_CAPABILITIES_LINO),
        ("data/seed/approved-lessons.lino", APPROVED_LESSONS_LINO),
        ("data/seed/brainstorm-seeds.lino", BRAINSTORM_SEEDS_LINO),
        ("data/seed/caller-context.lino", CALLER_CONTEXT_LINO),
        ("data/seed/client-completion-contracts.lino", CLIENT_COMPLETION_CONTRACTS_LINO),
        ("data/seed/client-integrations.lino", CLIENT_INTEGRATIONS_LINO),
        ("data/seed/coding-guidance.lino", CODING_GUIDANCE_LINO),
        ("data/seed/coding-idioms.lino", CODING_IDIOMS_LINO),
        ("data/seed/command-outcome.lino", COMMAND_OUTCOME_LINO),
        ("data/seed/computer-use-tasks.lino", COMPUTER_USE_TASKS_LINO),
        ("data/seed/concept-contexts.lino", CONCEPT_CONTEXTS_LINO),
        ("data/seed/concepts.lino", CONCEPTS_LINO),
        ("data/seed/contribution-artifacts.lino", CONTRIBUTION_ARTIFACTS_LINO),
        ("data/seed/coreference.lino", COREFERENCE_LINO),
        ("data/seed/demo-dialogs.lino", DEMO_DIALOGS_LINO),
        ("data/seed/draft-strategies.lino", DRAFT_STRATEGIES_LINO),
        ("data/seed/entity-names.lino", ENTITY_NAMES_LINO),
        ("data/seed/environments.lino", ENVIRONMENTS_LINO),
        ("data/seed/facts.lino", FACTS_LINO),
        ("data/seed/formal-language-projections.lino", FORMAL_LANGUAGE_PROJECTIONS_LINO),
        ("data/seed/formalization-relations.lino", FORMALIZATION_RELATIONS_LINO),
        ("data/seed/greetings.lino", GREETINGS_LINO),
        ("data/seed/handler-family-methods.lino", HANDLER_FAMILY_METHODS_LINO),
        ("data/seed/handler-precedence.lino", HANDLER_PRECEDENCE_LINO),
        ("data/seed/handler-promotions.lino", HANDLER_PROMOTIONS_LINO),
        ("data/seed/handler-rules.lino", HANDLER_RULES_LINO),
        ("data/seed/hello-world-programs.lino", HELLO_WORLD_PROGRAMS_LINO),
        ("data/seed/identity.lino", IDENTITY_LINO),
        ("data/seed/intent-routing.lino", INTENT_ROUTING_LINO),
        ("data/seed/interface-capabilities.lino", INTERFACE_CAPABILITIES_LINO),
        ("data/seed/language-detection.lino", LANGUAGE_DETECTION_LINO),
        ("data/seed/languages.lino", LANGUAGES_LINO),
        ("data/seed/learned-methods.lino", LEARNED_METHODS_LINO),
        ("data/seed/learned-program-rules.lino", LEARNED_PROGRAM_RULES_LINO),
        ("data/seed/learned-request-openers.lino", LEARNED_REQUEST_OPENERS_LINO),
        ("data/seed/learning-sources.lino", LEARNING_SOURCES_LINO),
        ("data/seed/market-price-references.lino", MARKET_PRICE_REFERENCES_LINO),
        ("data/seed/meanings.lino", MEANINGS_LINO),
        ("data/seed/meanings-acts.lino", MEANINGS_ACTS_LINO),
        ("data/seed/meanings-agent-actions.lino", MEANINGS_AGENT_ACTIONS_LINO),
        ("data/seed/meanings-behavior-rules.lino", MEANINGS_BEHAVIOR_RULES_LINO),
        ("data/seed/meanings-calculator.lino", MEANINGS_CALCULATOR_LINO),
        ("data/seed/meanings-calendar.lino", MEANINGS_CALENDAR_LINO),
        ("data/seed/meanings-coding-catalog.lino", MEANINGS_CODING_CATALOG_LINO),
        ("data/seed/meanings-coding-config.lino", MEANINGS_CODING_CONFIG_LINO),
        ("data/seed/meanings-coding-request.lino", MEANINGS_CODING_REQUEST_LINO),
        ("data/seed/meanings-coding-structure.lino", MEANINGS_CODING_STRUCTURE_LINO),
        ("data/seed/meanings-coding-structure-2.lino", MEANINGS_CODING_STRUCTURE_2_LINO),
        ("data/seed/meanings-coding-tasks.lino", MEANINGS_CODING_TASKS_LINO),
        ("data/seed/meanings-computer-use.lino", MEANINGS_COMPUTER_USE_LINO),
        ("data/seed/meanings-concept-lookup.lino", MEANINGS_CONCEPT_LOOKUP_LINO),
        ("data/seed/meanings-conversation.lino", MEANINGS_CONVERSATION_LINO),
        ("data/seed/meanings-decomposition.lino", MEANINGS_DECOMPOSITION_LINO),
        ("data/seed/meanings-definition-merge.lino", MEANINGS_DEFINITION_MERGE_LINO),
        ("data/seed/meanings-docs.lino", MEANINGS_DOCS_LINO),
        ("data/seed/meanings-facts.lino", MEANINGS_FACTS_LINO),
        ("data/seed/meanings-feature-capability.lino", MEANINGS_FEATURE_CAPABILITY_LINO),
        ("data/seed/meanings-file-edit.lino", MEANINGS_FILE_EDIT_LINO),
        ("data/seed/meanings-file-write.lino", MEANINGS_FILE_WRITE_LINO),
        ("data/seed/meanings-finance.lino", MEANINGS_FINANCE_LINO),
        ("data/seed/meanings-formalization-needs.lino", MEANINGS_FORMALIZATION_NEEDS_LINO),
        ("data/seed/meanings-formalization-relations.lino", MEANINGS_FORMALIZATION_RELATIONS_LINO),
        ("data/seed/meanings-formalization-report.lino", MEANINGS_FORMALIZATION_REPORT_LINO),
        ("data/seed/meanings-how.lino", MEANINGS_HOW_LINO),
        ("data/seed/meanings-intent.lino", MEANINGS_INTENT_LINO),
        ("data/seed/meanings-lexical-meta.lino", MEANINGS_LEXICAL_META_LINO),
        ("data/seed/meanings-lexicon-import-01.lino", MEANINGS_LEXICON_IMPORT_01_LINO),
        ("data/seed/meanings-lexicon-import-02.lino", MEANINGS_LEXICON_IMPORT_02_LINO),
        ("data/seed/meanings-lexicon-import-03.lino", MEANINGS_LEXICON_IMPORT_03_LINO),
        ("data/seed/meanings-lexicon-import-04.lino", MEANINGS_LEXICON_IMPORT_04_LINO),
        ("data/seed/meanings-links-root.lino", MEANINGS_LINKS_ROOT_LINO),
        ("data/seed/meanings-local-search.lino", MEANINGS_LOCAL_SEARCH_LINO),
        ("data/seed/meanings-membership.lino", MEANINGS_MEMBERSHIP_LINO),
        ("data/seed/meanings-meta.lino", MEANINGS_META_LINO),
        ("data/seed/meanings-note-composition.lino", MEANINGS_NOTE_COMPOSITION_LINO),
        ("data/seed/meanings-number-constraints.lino", MEANINGS_NUMBER_CONSTRAINTS_LINO),
        ("data/seed/meanings-object-shapes.lino", MEANINGS_OBJECT_SHAPES_LINO),
        ("data/seed/meanings-ontology.lino", MEANINGS_ONTOLOGY_LINO),
        ("data/seed/meanings-playwright.lino", MEANINGS_PLAYWRIGHT_LINO),
        ("data/seed/meanings-policy.lino", MEANINGS_POLICY_LINO),
        ("data/seed/meanings-program-synthesis.lino", MEANINGS_PROGRAM_SYNTHESIS_LINO),
        ("data/seed/meanings-proof.lino", MEANINGS_PROOF_LINO),
        ("data/seed/meanings-repository-workflow.lino", MEANINGS_REPOSITORY_WORKFLOW_LINO),
        ("data/seed/meanings-research-table.lino", MEANINGS_RESEARCH_TABLE_LINO),
        ("data/seed/meanings-routing-vocabulary.lino", MEANINGS_ROUTING_VOCABULARY_LINO),
        ("data/seed/meanings-selection-criteria.lino", MEANINGS_SELECTION_CRITERIA_LINO),
        ("data/seed/meanings-semantic-meta.lino", MEANINGS_SEMANTIC_META_LINO),
        ("data/seed/meanings-skill-compiler.lino", MEANINGS_SKILL_COMPILER_LINO),
        ("data/seed/meanings-skill-procedure.lino", MEANINGS_SKILL_PROCEDURE_LINO),
        ("data/seed/meanings-software-project.lino", MEANINGS_SOFTWARE_PROJECT_LINO),
        ("data/seed/meanings-statement-merge.lino", MEANINGS_STATEMENT_MERGE_LINO),
        ("data/seed/meanings-substitution-compiler.lino", MEANINGS_SUBSTITUTION_COMPILER_LINO),
        ("data/seed/meanings-summary.lino", MEANINGS_SUMMARY_LINO),
        ("data/seed/meanings-tool-access.lino", MEANINGS_TOOL_ACCESS_LINO),
        ("data/seed/meanings-translate-cycle.lino", MEANINGS_TRANSLATE_CYCLE_LINO),
        ("data/seed/meanings-translation.lino", MEANINGS_TRANSLATION_LINO),
        ("data/seed/meanings-units.lino", MEANINGS_UNITS_LINO),
        ("data/seed/meanings-verifiable-task.lino", MEANINGS_VERIFIABLE_TASK_LINO),
        ("data/seed/meanings-web-followup.lino", MEANINGS_WEB_FOLLOWUP_LINO),
        ("data/seed/meanings-web-navigation.lino", MEANINGS_WEB_NAVIGATION_LINO),
        ("data/seed/meanings-web-research.lino", MEANINGS_WEB_RESEARCH_LINO),
        ("data/seed/meanings-web-search.lino", MEANINGS_WEB_SEARCH_LINO),
        ("data/seed/meanings-web-search-query.lino", MEANINGS_WEB_SEARCH_QUERY_LINO),
        ("data/seed/meanings-wikidata.lino", MEANINGS_WIKIDATA_LINO),
        ("data/seed/meanings-writing-systems.lino", MEANINGS_WRITING_SYSTEMS_LINO),
        ("data/seed/memory-programs.lino", MEMORY_PROGRAMS_LINO),
        ("data/seed/method-execution.lino", METHOD_EXECUTION_LINO),
        ("data/seed/model-aliases.lino", MODEL_ALIASES_LINO),
        ("data/seed/multilingual-responses.lino", MULTILINGUAL_RESPONSES_LINO),
        ("data/seed/multilingual-responses-agentic.lino", MULTILINGUAL_RESPONSES_AGENTIC_LINO),
        (
            "data/seed/multilingual-responses-agentic-continuation.lino",
            MULTILINGUAL_RESPONSES_AGENTIC_CONTINUATION_LINO,
        ),
        (
            "data/seed/multilingual-responses-agentic-tools.lino",
            MULTILINGUAL_RESPONSES_AGENTIC_TOOLS_LINO,
        ),
        (
            "data/seed/multilingual-responses-client-config.lino",
            MULTILINGUAL_RESPONSES_CLIENT_CONFIG_LINO,
        ),
        (
            "data/seed/multilingual-responses-concept-lookup.lino",
            MULTILINGUAL_RESPONSES_CONCEPT_LOOKUP_LINO,
        ),
        (
            "data/seed/multilingual-responses-decomposition.lino",
            MULTILINGUAL_RESPONSES_DECOMPOSITION_LINO,
        ),
        ("data/seed/multilingual-responses-entities.lino", MULTILINGUAL_RESPONSES_ENTITIES_LINO),
        (
            "data/seed/multilingual-responses-external-benchmark.lino",
            MULTILINGUAL_RESPONSES_EXTERNAL_BENCHMARK_LINO,
        ),
        ("data/seed/multilingual-responses-issue-710.lino", MULTILINGUAL_RESPONSES_ISSUE_710_LINO),
        (
            "data/seed/multilingual-responses-language-protocol.lino",
            MULTILINGUAL_RESPONSES_LANGUAGE_PROTOCOL_LINO,
        ),
        (
            "data/seed/multilingual-responses-memory-program.lino",
            MULTILINGUAL_RESPONSES_MEMORY_PROGRAM_LINO,
        ),
        (
            "data/seed/multilingual-responses-orchestration.lino",
            MULTILINGUAL_RESPONSES_ORCHESTRATION_LINO,
        ),
        ("data/seed/multilingual-responses-parity.lino", MULTILINGUAL_RESPONSES_PARITY_LINO),
        ("data/seed/multilingual-responses-pattern.lino", MULTILINGUAL_RESPONSES_PATTERN_LINO),
        ("data/seed/multilingual-responses-policy.lino", MULTILINGUAL_RESPONSES_POLICY_LINO),
        ("data/seed/multilingual-responses-procedure.lino", MULTILINGUAL_RESPONSES_PROCEDURE_LINO),
        (
            "data/seed/multilingual-responses-substitution-compiler.lino",
            MULTILINGUAL_RESPONSES_SUBSTITUTION_COMPILER_LINO,
        ),
        (
            "data/seed/multilingual-responses-summarization.lino",
            MULTILINGUAL_RESPONSES_SUMMARIZATION_LINO,
        ),
        (
            "data/seed/multilingual-responses-summarization-quality.lino",
            MULTILINGUAL_RESPONSES_SUMMARIZATION_QUALITY_LINO,
        ),
        ("data/seed/multilingual-responses-symbolic.lino", MULTILINGUAL_RESPONSES_SYMBOLIC_LINO),
        ("data/seed/multilingual-responses-synthesis.lino", MULTILINGUAL_RESPONSES_SYNTHESIS_LINO),
        ("data/seed/multilingual-responses-thinking.lino", MULTILINGUAL_RESPONSES_THINKING_LINO),
        (
            "data/seed/multilingual-responses-thinking-narrative.lino",
            MULTILINGUAL_RESPONSES_THINKING_NARRATIVE_LINO,
        ),
        ("data/seed/multilingual-responses-translate.lino", MULTILINGUAL_RESPONSES_TRANSLATE_LINO),
        ("data/seed/numeric-list-operations.lino", NUMERIC_LIST_OPERATIONS_LINO),
        ("data/seed/obligation-mismatch.lino", OBLIGATION_MISMATCH_LINO),
        ("data/seed/operation-vocabulary.lino", OPERATION_VOCABULARY_LINO),
        ("data/seed/personas.lino", PERSONAS_LINO),
        ("data/seed/planner-precedence.lino", PLANNER_PRECEDENCE_LINO),
        ("data/seed/program-cst-grammars.lino", PROGRAM_CST_GRAMMARS_LINO),
        ("data/seed/program-plan-rules.lino", PROGRAM_PLAN_RULES_LINO),
        ("data/seed/projects.lino", PROJECTS_LINO),
        ("data/seed/prompt-patterns.lino", PROMPT_PATTERNS_LINO),
        ("data/seed/proof-program-templates.lino", PROOF_PROGRAM_TEMPLATES_LINO),
        ("data/seed/question-necessity.lino", QUESTION_NECESSITY_LINO),
        ("data/seed/release-timelines.lino", RELEASE_TIMELINES_LINO),
        ("data/seed/repository-command-allowlist.lino", REPOSITORY_COMMAND_ALLOWLIST_LINO),
        ("data/seed/research-table-procedure.lino", RESEARCH_TABLE_PROCEDURE_LINO),
        ("data/seed/self-improvement-loop.lino", SELF_IMPROVEMENT_LOOP_LINO),
        ("data/seed/sentence-punctuation.lino", SENTENCE_PUNCTUATION_LINO),
        ("data/seed/setup-publishers.lino", SETUP_PUBLISHERS_LINO),
        ("data/seed/shell-intents.lino", SHELL_INTENTS_LINO),
        ("data/seed/sources-registry.lino", SOURCES_REGISTRY_LINO),
        ("data/seed/summary-topics.lino", SUMMARY_TOPICS_LINO),
        ("data/seed/terminal-commands.lino", TERMINAL_COMMANDS_LINO),
        ("data/seed/tool-resource-scopes.lino", TOOL_RESOURCE_SCOPES_LINO),
        ("data/seed/toolchains.lino", TOOLCHAINS_LINO),
        ("data/seed/tools.lino", TOOLS_LINO),
        ("data/seed/triz-principles.lino", TRIZ_PRINCIPLES_LINO),
    ]
}

/// The registered set of multilingual-response files, walked by
/// [`super::multilingual_responses`].
///
/// Split so none breaches the seed file-size guard; each wraps its records
/// under a top-level `multilingual_responses` node and the parser walks all of
/// them, so an intent may live in whichever file keeps the sizes balanced.
pub const RESPONSE_FILES: &[&str] = &[
    MULTILINGUAL_RESPONSES_LINO,
    MULTILINGUAL_RESPONSES_AGENTIC_LINO,
    MULTILINGUAL_RESPONSES_AGENTIC_CONTINUATION_LINO,
    MULTILINGUAL_RESPONSES_AGENTIC_TOOLS_LINO,
    MULTILINGUAL_RESPONSES_CLIENT_CONFIG_LINO,
    MULTILINGUAL_RESPONSES_CONCEPT_LOOKUP_LINO,
    MULTILINGUAL_RESPONSES_DECOMPOSITION_LINO,
    MULTILINGUAL_RESPONSES_ENTITIES_LINO,
    MULTILINGUAL_RESPONSES_EXTERNAL_BENCHMARK_LINO,
    MULTILINGUAL_RESPONSES_ISSUE_710_LINO,
    MULTILINGUAL_RESPONSES_LANGUAGE_PROTOCOL_LINO,
    MULTILINGUAL_RESPONSES_MEMORY_PROGRAM_LINO,
    MULTILINGUAL_RESPONSES_ORCHESTRATION_LINO,
    MULTILINGUAL_RESPONSES_PARITY_LINO,
    MULTILINGUAL_RESPONSES_PATTERN_LINO,
    MULTILINGUAL_RESPONSES_POLICY_LINO,
    MULTILINGUAL_RESPONSES_PROCEDURE_LINO,
    MULTILINGUAL_RESPONSES_SUBSTITUTION_COMPILER_LINO,
    MULTILINGUAL_RESPONSES_SUMMARIZATION_LINO,
    MULTILINGUAL_RESPONSES_SUMMARIZATION_QUALITY_LINO,
    MULTILINGUAL_RESPONSES_SYMBOLIC_LINO,
    MULTILINGUAL_RESPONSES_SYNTHESIS_LINO,
    MULTILINGUAL_RESPONSES_THINKING_LINO,
    MULTILINGUAL_RESPONSES_THINKING_NARRATIVE_LINO,
    MULTILINGUAL_RESPONSES_TRANSLATE_LINO,
];

/// The registered set of meaning-lexicon files, concatenated by
/// [`super::lexicon`].
///
/// Split across several `.lino` files so none breaches the seed file-size
/// guard; each wraps its records under a top-level `meanings` node (the loader
/// walks all of them).
pub const MEANING_FILES: &[&str] = &[
    LEARNED_REQUEST_OPENERS_LINO,
    MEANINGS_LINO,
    MEANINGS_ACTS_LINO,
    MEANINGS_AGENT_ACTIONS_LINO,
    MEANINGS_BEHAVIOR_RULES_LINO,
    MEANINGS_CALCULATOR_LINO,
    MEANINGS_CALENDAR_LINO,
    MEANINGS_CODING_CATALOG_LINO,
    MEANINGS_CODING_CONFIG_LINO,
    MEANINGS_CODING_REQUEST_LINO,
    MEANINGS_CODING_STRUCTURE_LINO,
    MEANINGS_CODING_STRUCTURE_2_LINO,
    MEANINGS_CODING_TASKS_LINO,
    MEANINGS_COMPUTER_USE_LINO,
    MEANINGS_CONCEPT_LOOKUP_LINO,
    MEANINGS_CONVERSATION_LINO,
    MEANINGS_DECOMPOSITION_LINO,
    MEANINGS_DEFINITION_MERGE_LINO,
    MEANINGS_DOCS_LINO,
    MEANINGS_FACTS_LINO,
    MEANINGS_FEATURE_CAPABILITY_LINO,
    MEANINGS_FILE_EDIT_LINO,
    MEANINGS_FILE_WRITE_LINO,
    MEANINGS_FINANCE_LINO,
    MEANINGS_FORMALIZATION_NEEDS_LINO,
    MEANINGS_FORMALIZATION_RELATIONS_LINO,
    MEANINGS_FORMALIZATION_REPORT_LINO,
    MEANINGS_HOW_LINO,
    MEANINGS_INTENT_LINO,
    MEANINGS_LEXICAL_META_LINO,
    MEANINGS_LEXICON_IMPORT_01_LINO,
    MEANINGS_LEXICON_IMPORT_02_LINO,
    MEANINGS_LEXICON_IMPORT_03_LINO,
    MEANINGS_LEXICON_IMPORT_04_LINO,
    MEANINGS_LINKS_ROOT_LINO,
    MEANINGS_LOCAL_SEARCH_LINO,
    MEANINGS_MEMBERSHIP_LINO,
    MEANINGS_META_LINO,
    MEANINGS_NOTE_COMPOSITION_LINO,
    MEANINGS_NUMBER_CONSTRAINTS_LINO,
    MEANINGS_OBJECT_SHAPES_LINO,
    MEANINGS_ONTOLOGY_LINO,
    MEANINGS_PLAYWRIGHT_LINO,
    MEANINGS_POLICY_LINO,
    MEANINGS_PROGRAM_SYNTHESIS_LINO,
    MEANINGS_PROOF_LINO,
    MEANINGS_REPOSITORY_WORKFLOW_LINO,
    MEANINGS_RESEARCH_TABLE_LINO,
    MEANINGS_ROUTING_VOCABULARY_LINO,
    MEANINGS_SEARCH_LINO,
    MEANINGS_SELECTION_CRITERIA_LINO,
    MEANINGS_SEMANTIC_META_LINO,
    MEANINGS_SKILL_COMPILER_LINO,
    MEANINGS_SKILL_PROCEDURE_LINO,
    MEANINGS_SOFTWARE_PROJECT_LINO,
    MEANINGS_STATEMENT_MERGE_LINO,
    MEANINGS_SUBSTITUTION_COMPILER_LINO,
    MEANINGS_SUMMARY_LINO,
    MEANINGS_TOOL_ACCESS_LINO,
    MEANINGS_TRANSLATE_CYCLE_LINO,
    MEANINGS_TRANSLATION_LINO,
    MEANINGS_UNITS_LINO,
    MEANINGS_VERIFIABLE_TASK_LINO,
    MEANINGS_WEB_FOLLOWUP_LINO,
    MEANINGS_WEB_NAVIGATION_LINO,
    MEANINGS_WEB_RESEARCH_LINO,
    MEANINGS_WEB_SEARCH_LINO,
    MEANINGS_WEB_SEARCH_QUERY_LINO,
    MEANINGS_WIKIDATA_LINO,
    MEANINGS_WRITING_SYSTEMS_LINO,
];
