//! Issue #386: regenerate the `no_std` arithmetic word→value tables.
//!
//! The arithmetic evaluator (`src/arithmetic.rs`) rewrites a spelled expression
//! ("two plus three", "пять умножить на два") into its symbolic form ("2 + 3",
//! "5 * 2") before tokenizing. The word→value mapping is **not** hardcoded in
//! the evaluator: it is derived from the seed meanings (the `cardinal_number`
//! digits and the `arithmetic_operation` operators), where each meaning carries
//! its script-independent value surface as a word form — the numeral "2", the
//! symbol "+".
//!
//! But the evaluator is compiled into the wasm worker
//! (`src/web/wasm-worker/src/lib.rs` `#[path]`-includes `arithmetic.rs`), which
//! is `#![no_std]` and cannot reach the seed loader at runtime — and the wasm
//! build is plain `rustc`, so there is no `build.rs` to generate code either.
//! The table is therefore materialized here, at author time, into a `no_std`
//! static the evaluator `include!`s in both builds. Parity with the live seed
//! is enforced by the `arithmetic_word_tables_match_seed` test in
//! `src/calculation.rs`, so a stale table fails CI.
//!
//! Run after editing the cardinal/operator meanings in
//! `data/seed/meanings-units.lino` / `data/seed/meanings-calculator.lino`:
//!
//! ```sh
//! cargo run -p formal-ai --example issue_386_gen_arith_table
//! ```
use std::fmt::Write as _;
use std::path::Path;

use formal_ai::seed;

fn main() {
    let (tokens, phrases) = seed::lexicon().arithmetic_normalization_tables();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p formal-ai --example issue_386_gen_arith_table`.\n\
         // DO NOT EDIT BY HAND. Edit the cardinal/operator meanings in\n\
         // data/seed/meanings-units.lino and data/seed/meanings-calculator.lino,\n\
         // then regenerate. Parity with the live seed is enforced by the\n\
         // `arithmetic_word_tables_match_seed` test in src/calculation.rs.\n\
         //\n\
         // These tables drive `normalize_expression` in src/arithmetic.rs, which is\n\
         // compiled into the wasm worker and so must stay no_std + alloc only.\n\n",
    );
    emit(
        &mut out,
        "// Single-word surfaces, mapped to the value surface of their meaning (a\n\
         // spelled digit or operator word to its numeral/symbol). Applied after the\n\
         // expression is split on whitespace. Sorted by surface for a stable diff.\n",
        "WORD_VALUE_TOKENS",
        &tokens,
    );
    out.push('\n');
    emit(
        &mut out,
        "// Multi-word operator phrases, mapped to their operator symbol and applied\n\
         // before tokenization. Longest first so a phrase is rewritten before any\n\
         // shorter phrase it contains (\"разделить на\" before \"делить на\").\n",
        "WORD_VALUE_PHRASES",
        &phrases,
    );

    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/arithmetic_word_tables.rs");
    std::fs::write(&path, &out).expect("write src/arithmetic_word_tables.rs");
    println!(
        "wrote {} ({} tokens, {} phrases)",
        path.display(),
        tokens.len(),
        phrases.len()
    );
}

/// Append a `pub(crate) static NAME: &[(&str, &str)] = &[...];` block with the
/// given documentation header.
fn emit(out: &mut String, doc: &str, name: &str, rows: &[(String, String)]) {
    out.push_str(doc);
    let _ = writeln!(out, "pub(crate) static {name}: &[(&str, &str)] = &[");
    for (surface, value) in rows {
        let _ = writeln!(out, "    ({surface:?}, {value:?}),");
    }
    out.push_str("];\n");
}
