#!/usr/bin/env rust-script
//! Assemble `REQUIREMENTS.md` from one shard per issue.
//!
//! Issue #991: `REQUIREMENTS.md` was the repository's worst append-only
//! document. Every issue adds a `## Issue #N ...` section, every branch adds it
//! at the end of the same file, and so two unrelated issues collide on the same
//! end-of-file region. `scripts/analyze-merge-conflicts.py` counted 64 manual
//! resolutions in this one file.
//!
//! The fix is to give each section its own file under `docs/requirements/` and
//! make `REQUIREMENTS.md` a derived artifact. Two branches writing requirements
//! for two different issues now create two different files and cannot conflict.
//!
//! Shards are assembled in a total order read entirely from the file name, so
//! there is no shared index file to conflict on either:
//!
//! | prefix      | position | sorted by                             |
//! | ----------- | -------- | ------------------------------------- |
//! | `preamble-` | first    | file name                             |
//! | `issue-`    | middle   | zero-padded issue number, then slug    |
//! | `doctrine-` | last     | file name                             |
//!
//! The assembled register is itself split. The maintainer's rule is that no
//! maintained file may exceed 1500 lines, and the register outgrew that, so the
//! sections are packed, in assembly order and never cut in half, into
//! `docs/requirements/assembled/part-NN.md` files of at most
//! `PART_LINE_LIMIT` lines. `REQUIREMENTS.md` is the index: it links every part
//! and lists the sections each one holds. Reading the parts in name order gives
//! the whole register; readers do exactly that rather than reading the index.
//!
//! Usage:
//!   rust-script scripts/assemble-requirements.rs           # check the index and parts are current
//!   rust-script scripts/assemble-requirements.rs --write   # rebuild the index and parts
//!   rust-script scripts/assemble-requirements.rs --split   # re-shard the assembled parts
//!
//! ```cargo
//! [package]
//! edition = "2024"
//!
//! [dependencies]
//! ```

use std::fs;
use std::path::{Path, PathBuf};

#[cfg(not(test))]
const DOCUMENT: &str = "REQUIREMENTS.md";
const SHARDS: &str = "docs/requirements";
/// Where the assembled register lives, one ordered part per file.
const PARTS: &str = "docs/requirements/assembled";
/// The most lines one part may hold: under the 1500-line cap and under the
/// 1400-line warning threshold of `scripts/check-file-size.rs`.
const PART_LINE_LIMIT: usize = 1_400;
/// The banner, a blank line, the navigation line, and a blank line.
const PART_HEADER_LINES: usize = 4;
const BANNER: &str = "<!-- Generated by `rust-script scripts/assemble-requirements.rs --write` from `docs/requirements/`. Edit the shard for your issue, never this file: see `data/meta/merge-conflict-policy.lino`. -->";

/// Where a shard sits in the assembled document, read from its file name.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Group {
    Preamble,
    Issue(u32),
    Doctrine,
}

/// The total order of a shard: group first, then the file name inside it.
fn shard_order(file_name: &str) -> Option<(Group, String)> {
    let stem = file_name.strip_suffix(".md")?;
    let group = if let Some(rest) = stem.strip_prefix("issue-") {
        let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
        Group::Issue(digits.parse().ok()?)
    } else if stem.starts_with("preamble-") {
        Group::Preamble
    } else if stem.starts_with("doctrine-") {
        Group::Doctrine
    } else {
        return None;
    };
    Some((group, stem.to_string()))
}

/// The issue number a section heading claims, if it names one.
fn heading_issue(heading: &str) -> Option<u32> {
    let rest = heading.split_once("Issue #")?.1;
    let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
    digits.parse().ok()
}

/// A file-name-safe slug for a section heading.
fn slug(heading: &str) -> String {
    let mut slug = String::new();
    for character in heading.chars() {
        if character.is_ascii_alphanumeric() {
            slug.push(character.to_ascii_lowercase());
        } else if !slug.ends_with('-') {
            slug.push('-');
        }
    }
    slug.trim_matches('-').to_string()
}

/// Split a document into its leading preamble and its `## ` sections.
fn sections(document: &str) -> (String, Vec<String>) {
    let mut preamble = String::new();
    let mut sections: Vec<String> = Vec::new();
    for line in document.lines() {
        if line.starts_with("## ") {
            sections.push(String::new());
        }
        let target = sections.last_mut().unwrap_or(&mut preamble);
        target.push_str(line);
        target.push('\n');
    }
    (preamble, sections)
}

/// The shard file name for a section, derived from its heading.
fn shard_name(heading: &str) -> String {
    let title = heading.trim_start_matches('#').trim();
    match heading_issue(heading) {
        Some(issue) => {
            let subject = title
                .strip_prefix(&format!("Issue #{issue}"))
                .unwrap_or(title);
            format!("issue-{issue:04}-{}.md", slug(subject))
        }
        None => format!("doctrine-{}.md", slug(title)),
    }
}

/// Whether a markdown link target is resolved against the file that holds it.
///
/// An absolute URL, an in-page anchor, and a root-anchored path all mean the
/// same thing wherever the text ends up, so only these are left untouched.
fn is_document_relative(target: &str) -> bool {
    !(target.is_empty()
        || target.starts_with('#')
        || target.starts_with('/')
        || target.contains("://")
        || target.starts_with("mailto:"))
}

/// Resolve `.` and `..` segments textually, without touching the filesystem.
fn normalize(path: &str) -> String {
    let mut parts: Vec<&str> = Vec::new();
    for part in path.split('/') {
        match part {
            "" | "." => {}
            ".." if matches!(parts.last(), Some(&last) if last != "..") => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

/// A shard's link target as the repository root sees it.
///
/// A shard is a document in its own right: it is read in an editor and rendered
/// on its own page, so its links are written relative to `docs/requirements/`.
/// `REQUIREMENTS.md` is assembled at the repository root, so the same target
/// has to be rebased on the way in.
fn to_root_relative(target: &str) -> String {
    if !is_document_relative(target) {
        return target.to_string();
    }
    normalize(&format!("{SHARDS}/{target}"))
}

/// A root-relative link target as a document in the directory `base` has to
/// write it.
fn relative_to(base: &str, target: &str) -> String {
    if !is_document_relative(target) {
        return target.to_string();
    }
    let target = normalize(target);
    let base: Vec<&str> = base.split('/').collect();
    let parts: Vec<&str> = target.split('/').collect();
    let shared = base
        .iter()
        .zip(&parts)
        .take_while(|(left, right)| left == right)
        .count();
    let mut rebased: Vec<&str> = vec![".."; base.len() - shared];
    rebased.extend(&parts[shared..]);
    // A link to the directory itself has nothing left to say once it is rebased
    // into that directory; an empty target is a broken link, `.` is not.
    if rebased.is_empty() {
        return ".".to_string();
    }
    rebased.join("/")
}

/// The inverse: a root document's link target as a shard has to write it.
fn to_shard_relative(target: &str) -> String {
    relative_to(SHARDS, target)
}

/// A shard's link target as an assembled part, which sits one directory below
/// the shards, has to write it.
fn shard_to_part_relative(target: &str) -> String {
    if !is_document_relative(target) {
        return target.to_string();
    }
    relative_to(PARTS, &to_root_relative(target))
}

/// A part's link target as a shard has to write it: the inverse, for `--split`.
#[cfg(not(test))]
fn part_to_shard_relative(target: &str) -> String {
    if !is_document_relative(target) {
        return target.to_string();
    }
    to_shard_relative(&normalize(&format!("{PARTS}/{target}")))
}

/// Rewrite every markdown link target in `body` through `rebase`.
///
/// Only `](target)` is rewritten; a reference definition or an autolink names no
/// relative path in this document, and a target holding a `)` is left alone
/// rather than guessed at.
fn rewrite_links(body: &str, rebase: &dyn Fn(&str) -> String) -> String {
    let mut rewritten = String::with_capacity(body.len());
    let mut rest = body;
    while let Some(open) = rest.find("](") {
        let after = &rest[open + 2..];
        let Some(close) = after.find(')') else {
            break;
        };
        let (target, title) = match after[..close].split_once(char::is_whitespace) {
            Some((target, title)) => (target, format!(" {title}")),
            None => (&after[..close], String::new()),
        };
        rewritten.push_str(&rest[..open + 2]);
        rewritten.push_str(&rebase(target));
        rewritten.push_str(&title);
        rewritten.push(')');
        rest = &after[close + 1..];
    }
    rewritten.push_str(rest);
    rewritten
}

/// Read the shard directory in assembly order.
fn ordered_shards(directory: &Path) -> Result<Vec<PathBuf>, String> {
    let mut shards: Vec<(Group, String, PathBuf)> = Vec::new();
    let entries =
        fs::read_dir(directory).map_err(|error| format!("cannot read {SHARDS}: {error}"))?;
    for entry in entries {
        let path = entry.map_err(|error| error.to_string())?.path();
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !file_name.ends_with(".md") || file_name == "README.md" {
            continue;
        }
        let (group, key) = shard_order(file_name).ok_or_else(|| {
            format!(
                "{SHARDS}/{file_name} must start with `preamble-`, `issue-NNNN-` or `doctrine-`"
            )
        })?;
        shards.push((group, key, path));
    }
    shards.sort();
    Ok(shards.into_iter().map(|(_, _, path)| path).collect())
}

/// The file name of the part numbered `number` (counting from one).
fn part_name(number: usize) -> String {
    format!("part-{number:02}.md")
}

/// The lines every part opens with: the banner and where the index is.
fn part_header(number: usize, total: usize) -> String {
    format!(
        "{BANNER}\n\nPart {number} of {total} of the assembled requirement register; \
         [`REQUIREMENTS.md`](../../../REQUIREMENTS.md) lists every part.\n\n"
    )
}

/// Pack section sizes, in order, into consecutive parts of at most
/// `PART_LINE_LIMIT` lines each. A section is never cut in half.
fn pack(sizes: &[(String, usize)]) -> Result<Vec<Vec<usize>>, String> {
    let mut parts: Vec<Vec<usize>> = Vec::new();
    let mut lines = 0;
    for (index, (name, size)) in sizes.iter().enumerate() {
        if PART_HEADER_LINES + size > PART_LINE_LIMIT {
            return Err(format!(
                "{SHARDS}/{name} has {size} lines, but an assembled part holds at most {} lines \
                 of shards; split the shard",
                PART_LINE_LIMIT - PART_HEADER_LINES
            ));
        }
        match parts.last_mut() {
            // One blank line separates a section from the one before it.
            Some(part) if lines + 1 + size <= PART_LINE_LIMIT => {
                part.push(index);
                lines += 1 + size;
            }
            _ => {
                parts.push(vec![index]);
                lines = PART_HEADER_LINES + size;
            }
        }
    }
    Ok(parts)
}

/// The assembled register: the index document and its ordered parts.
#[derive(Debug, PartialEq, Eq)]
struct Assembly {
    index: String,
    /// `(file name, text)` in reading order.
    parts: Vec<(String, String)>,
}

/// The heading a section opens with, as plain text for the index.
fn section_title(body: &str) -> String {
    body.lines()
        .find(|line| line.starts_with('#'))
        .unwrap_or_default()
        .trim_start_matches('#')
        .trim()
        .to_string()
}

/// The index: every part, in order, with the sections it holds.
fn index_document(parts: &[Vec<usize>], titles: &[String]) -> String {
    let mut index = format!(
        "{BANNER}\n\n# Requirements\n\n\
         The requirement register is assembled from one shard per issue under\n\
         [`docs/requirements/`](docs/requirements/README.md). No maintained file may exceed\n\
         1500 lines, so the assembled register is split into ordered parts. Read them in\n\
         order: together they are the whole register.\n"
    );
    for (number, part) in parts.iter().enumerate() {
        let number = number + 1;
        index.push_str(&format!(
            "\n{number}. [Part {number}]({PARTS}/{})\n",
            part_name(number)
        ));
        for &section in part {
            index.push_str(&format!("   - {}\n", titles[section]));
        }
    }
    index
}

/// The register the shards currently describe.
fn assemble(shards: &[PathBuf]) -> Result<Assembly, String> {
    let mut bodies: Vec<String> = Vec::new();
    let mut sizes: Vec<(String, usize)> = Vec::new();
    for shard in shards {
        let body = fs::read_to_string(shard)
            .map_err(|error| format!("cannot read {}: {error}", shard.display()))?;
        let body = body.trim_end_matches('\n').to_string();
        let name = shard
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_string();
        sizes.push((name, body.lines().count()));
        bodies.push(body);
    }
    let packed = pack(&sizes)?;
    let titles: Vec<String> = bodies
        .iter()
        .map(|body| section_title(&rewrite_links(body, &to_root_relative)))
        .collect();
    let total = packed.len();
    let parts = packed
        .iter()
        .enumerate()
        .map(|(number, part)| {
            let sections: Vec<String> = part
                .iter()
                .map(|&section| rewrite_links(&bodies[section], &shard_to_part_relative))
                .collect();
            let text = format!(
                "{}{}\n",
                part_header(number + 1, total),
                sections.join("\n\n")
            );
            (part_name(number + 1), text)
        })
        .collect();
    Ok(Assembly {
        index: index_document(&packed, &titles),
        parts,
    })
}

/// The part files present on disk, in reading order.
#[cfg(not(test))]
fn existing_parts(directory: &Path) -> Vec<PathBuf> {
    let mut parts: Vec<PathBuf> = fs::read_dir(directory)
        .map(|entries| {
            entries
                .filter_map(Result::ok)
                .map(|entry| entry.path())
                .filter(|path| {
                    path.file_name()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| name.starts_with("part-") && name.ends_with(".md"))
                })
                .collect()
        })
        .unwrap_or_default();
    parts.sort();
    parts
}

/// Every difference between the assembly and what is on disk, as messages.
#[cfg(not(test))]
fn drift(root: &Path, assembly: &Assembly) -> Vec<String> {
    let mut drifted = Vec::new();
    if fs::read_to_string(root.join(DOCUMENT)).unwrap_or_default() != assembly.index {
        drifted.push(DOCUMENT.to_string());
    }
    for (name, text) in &assembly.parts {
        let path = root.join(PARTS).join(name);
        if fs::read_to_string(&path).unwrap_or_default() != *text {
            drifted.push(format!("{PARTS}/{name}"));
        }
    }
    for path in existing_parts(&root.join(PARTS)) {
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default();
        if !assembly.parts.iter().any(|(part, _)| part == name) {
            drifted.push(format!("{PARTS}/{name} (stale)"));
        }
    }
    drifted
}

/// Every rule a shard directory has to satisfy.
fn shard_violations(shards: &[PathBuf], read: &dyn Fn(&Path) -> String) -> Vec<String> {
    let mut failures = Vec::new();
    for shard in shards {
        let name = shard
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default();
        let body = read(shard);
        let heading = body.lines().next().unwrap_or_default();
        let Some(issue) = heading_issue(heading) else {
            continue;
        };
        if !heading.starts_with("## ") {
            continue;
        }
        if !name.starts_with(&format!("issue-{issue:04}-")) {
            failures.push(format!(
                "{SHARDS}/{name} starts with the heading `{heading}`, so it must be named \
                 `issue-{issue:04}-<slug>.md`"
            ));
        }
    }
    failures
}

/// Every document-relative link target in `body`, anchors stripped.
fn document_relative_targets(body: &str) -> Vec<String> {
    let mut targets = Vec::new();
    let mut rest = body;
    while let Some(open) = rest.find("](") {
        let after = &rest[open + 2..];
        let Some(close) = after.find(')') else {
            break;
        };
        let target = after[..close]
            .split_whitespace()
            .next()
            .unwrap_or_default()
            .split('#')
            .next()
            .unwrap_or_default();
        if is_document_relative(target) {
            targets.push(target.to_string());
        }
        rest = &after[close + 1..];
    }
    targets
}

/// A shard's relative links have to resolve from the shard's own directory.
///
/// A shard is read on its own page as well as through the assembled document,
/// and the repository's link checker reads it there. Checking it here names the
/// shard that broke the link instead of reporting a path that exists nowhere.
fn link_violations(
    shards: &[PathBuf],
    read: &dyn Fn(&Path) -> String,
    exists: &dyn Fn(&Path) -> bool,
) -> Vec<String> {
    let mut failures = Vec::new();
    for shard in shards {
        let directory = shard.parent().unwrap_or(Path::new("."));
        let name = shard
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default();
        for target in document_relative_targets(&read(shard)) {
            if !exists(&directory.join(&target)) {
                failures.push(format!(
                    "{SHARDS}/{name} links to `{target}`, which does not exist relative to \
                     {SHARDS}/. Write shard links relative to the shard; assembly rebases \
                     them to `{}`.",
                    to_root_relative(&target)
                ));
            }
        }
    }
    failures
}

/// The assembled register as one document: its parts in order, headers
/// removed, links rebased to the shard directory.
#[cfg(not(test))]
fn assembled_register(root: &Path) -> Result<String, String> {
    let parts = existing_parts(&root.join(PARTS));
    if parts.is_empty() {
        return Err(format!("{PARTS}/ holds no part-NN.md files"));
    }
    let mut sections = Vec::new();
    for part in parts {
        let text = fs::read_to_string(&part)
            .map_err(|error| format!("cannot read {}: {error}", part.display()))?;
        let body: Vec<&str> = text.lines().skip(PART_HEADER_LINES).collect();
        sections.push(body.join("\n"));
    }
    Ok(rewrite_links(
        &format!("{}\n", sections.join("\n\n")),
        &part_to_shard_relative,
    ))
}

/// Write the current register out as one file per section.
#[cfg(not(test))]
fn split(root: &Path) -> Result<usize, String> {
    let document = assembled_register(root)?;
    let (preamble, sections) = sections(&document);
    let directory = root.join(SHARDS);
    fs::create_dir_all(&directory).map_err(|error| error.to_string())?;

    let mut written = 0;
    let title = preamble.lines().next().unwrap_or("# Requirements");
    let name = format!("preamble-{}.md", slug(title));
    write_shard(&directory.join(&name), &preamble)?;
    written += 1;

    for section in &sections {
        let heading = section.lines().next().unwrap_or_default();
        write_shard(&directory.join(shard_name(heading)), section)?;
        written += 1;
    }
    Ok(written)
}

#[cfg(not(test))]
fn write_shard(path: &Path, body: &str) -> Result<(), String> {
    if path.exists() {
        return Err(format!(
            "{} already exists; two sections produced the same shard name",
            path.display()
        ));
    }
    let body = format!("{}\n", body.trim_end_matches('\n'));
    fs::write(path, body).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

#[cfg(not(test))]
fn main() {
    let root = std::env::current_dir().expect("Failed to get current directory");
    let mode = std::env::args().nth(1).unwrap_or_default();

    if mode == "--split" {
        match split(&root) {
            Ok(written) => {
                println!("\nWrote {written} shard(s) to {SHARDS}/.\n");
                return;
            }
            Err(error) => {
                println!("::error::{error}");
                std::process::exit(1);
            }
        }
    }

    let shards = ordered_shards(&root.join(SHARDS)).unwrap_or_else(|error| {
        println!("::error::{error}");
        std::process::exit(1);
    });
    let read = |path: &Path| fs::read_to_string(path).unwrap_or_default();
    let mut failures = shard_violations(&shards, &read);
    failures.extend(link_violations(&shards, &read, &|path| path.exists()));
    if !failures.is_empty() {
        for failure in &failures {
            println!("::error::{failure}");
        }
        std::process::exit(1);
    }

    let assembly = assemble(&shards).unwrap_or_else(|error| {
        println!("::error::{error}");
        std::process::exit(1);
    });
    let drifted = drift(&root, &assembly);

    if mode == "--write" {
        if drifted.is_empty() {
            println!(
                "\n{DOCUMENT} and {} part(s) are already current ({} shards).\n",
                assembly.parts.len(),
                shards.len()
            );
            return;
        }
        fs::write(root.join(DOCUMENT), &assembly.index).expect("Failed to write REQUIREMENTS.md");
        let parts = root.join(PARTS);
        fs::create_dir_all(&parts).expect("Failed to create the assembled parts directory");
        for stale in existing_parts(&parts) {
            fs::remove_file(&stale).expect("Failed to remove a stale part");
        }
        for (name, text) in &assembly.parts {
            fs::write(parts.join(name), text).expect("Failed to write an assembled part");
        }
        println!(
            "\nRebuilt {DOCUMENT} and {} part(s) in {PARTS}/ from {} shards.\n",
            assembly.parts.len(),
            shards.len()
        );
        return;
    }

    println!("\nChecking {DOCUMENT} and {PARTS}/ against {SHARDS}/ ({} shards)...\n", shards.len());
    if drifted.is_empty() {
        println!("{DOCUMENT} and its {} part(s) match the shards.\n", assembly.parts.len());
        return;
    }
    for path in &drifted {
        println!("::error::{path} does not match {SHARDS}/.");
    }
    println!("\nRun: rust-script scripts/assemble-requirements.rs --write\n");
    std::process::exit(1);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_preamble_sorts_first_then_issues_by_number_then_doctrine() {
        let mut names = vec![
            "doctrine-compiled-logic.md",
            "issue-0991-how-to-synthesis.md",
            "preamble-requirements-for-issue-1.md",
            "issue-0016-multilingual.md",
            "issue-0016-follow-up.md",
        ];
        names.sort_by_key(|name| shard_order(name).expect("named correctly"));
        assert_eq!(
            names,
            [
                "preamble-requirements-for-issue-1.md",
                "issue-0016-follow-up.md",
                "issue-0016-multilingual.md",
                "issue-0991-how-to-synthesis.md",
                "doctrine-compiled-logic.md",
            ]
        );
    }

    #[test]
    fn issue_numbers_order_numerically_not_lexicographically() {
        assert!(shard_order("issue-0016-a.md") < shard_order("issue-0117-a.md"));
        assert!(shard_order("issue-0991-a.md") < shard_order("issue-1000-a.md"));
    }

    #[test]
    fn an_unprefixed_shard_name_is_rejected() {
        assert_eq!(shard_order("current-scope-boundary.md"), None);
        assert_eq!(shard_order("issue-0991-notes.txt"), None);
    }

    #[test]
    fn a_heading_names_the_first_issue_it_mentions() {
        assert_eq!(
            heading_issue("## Issue #16 Follow-Up: Universal Data/Seed (PR #17 reopen)"),
            Some(16)
        );
        assert_eq!(
            heading_issue("## Issue #398 PR Review Standards (comment 4663407299)"),
            Some(398)
        );
        assert_eq!(heading_issue("## Current Scope Boundary"), None);
    }

    #[test]
    fn a_shard_name_is_derived_from_its_heading() {
        assert_eq!(
            shard_name("## Issue #991 Dynamic Multi-Source How-To Synthesis"),
            "issue-0991-dynamic-multi-source-how-to-synthesis.md"
        );
        assert_eq!(
            shard_name("## Standing Doctrine: Compiled Logic (2026-08-04)"),
            "doctrine-standing-doctrine-compiled-logic-2026-08-04.md"
        );
    }

    #[test]
    fn splitting_keeps_the_preamble_apart_from_the_sections() {
        let (preamble, sections) = sections("# Title\n\nIntro.\n\n## One\n\na\n\n## Two\n\nb\n");
        assert_eq!(preamble, "# Title\n\nIntro.\n\n");
        assert_eq!(sections, ["## One\n\na\n\n", "## Two\n\nb\n"]);
    }

    #[test]
    fn assembly_separates_sections_by_exactly_one_blank_line() {
        let directory = std::env::temp_dir().join("assemble-requirements-blank-lines");
        let _ = fs::remove_dir_all(&directory);
        fs::create_dir_all(&directory).expect("temp dir");
        fs::write(directory.join("preamble-a.md"), "# Title\n\nIntro.\n").expect("write");
        fs::write(directory.join("issue-0002-b.md"), "## Issue #2\n\nb\n\n\n").expect("write");
        let shards = ordered_shards(&directory).expect("ordered");
        let assembly = assemble(&shards).expect("assembled");
        assert_eq!(assembly.parts.len(), 1);
        assert_eq!(assembly.parts[0].0, "part-01.md");
        assert_eq!(
            assembly.parts[0].1,
            format!("{}# Title\n\nIntro.\n\n## Issue #2\n\nb\n", part_header(1, 1))
        );
        assert!(assembly.index.contains("1. [Part 1](docs/requirements/assembled/part-01.md)\n"));
        assert!(assembly.index.contains("   - Title\n   - Issue #2\n"));
        let _ = fs::remove_dir_all(&directory);
    }

    #[test]
    fn a_part_header_is_exactly_its_counted_lines() {
        assert_eq!(part_header(2, 3).lines().count(), PART_HEADER_LINES);
    }

    #[test]
    fn sections_pack_in_order_and_no_part_exceeds_the_limit() {
        let half = PART_LINE_LIMIT / 2;
        let sizes = vec![
            ("preamble-a.md".to_string(), 10),
            ("issue-0001-a.md".to_string(), half),
            ("issue-0002-a.md".to_string(), half),
            ("issue-0003-a.md".to_string(), 5),
        ];
        let parts = pack(&sizes).expect("packed");
        assert_eq!(parts, vec![vec![0, 1], vec![2, 3]]);
        for part in &parts {
            let lines = PART_HEADER_LINES
                + part.iter().map(|&index| sizes[index].1).sum::<usize>()
                + part.len()
                - 1;
            assert!(lines <= PART_LINE_LIMIT, "{lines} lines in {part:?}");
        }
    }

    #[test]
    fn a_section_too_large_for_any_part_is_rejected() {
        let sizes = vec![("issue-0001-huge.md".to_string(), PART_LINE_LIMIT)];
        let error = pack(&sizes).expect_err("too large");
        assert!(error.contains("issue-0001-huge.md"), "{error}");
    }

    #[test]
    fn a_shard_link_is_rebased_into_the_parts_directory() {
        for (shard, part) in [
            ("../upload-memory.md", "../../upload-memory.md"),
            ("../../scripts/close-total.py", "../../../scripts/close-total.py"),
            ("issue-0709-fusion.md", "../issue-0709-fusion.md"),
            ("https://example.org/a.md", "https://example.org/a.md"),
            ("#anchor", "#anchor"),
        ] {
            assert_eq!(shard_to_part_relative(shard), part, "{shard} lands in a part as {part}");
        }
    }

    #[test]
    fn a_shard_link_is_rebased_to_the_repository_root_and_back() {
        for (shard, root) in [
            ("../upload-memory.md", "docs/upload-memory.md"),
            ("../design/coverage-ratchet.md", "docs/design/coverage-ratchet.md"),
            (
                "../requirements-traceability.md",
                "docs/requirements-traceability.md",
            ),
            ("../../scripts/close-total.py", "scripts/close-total.py"),
            ("issue-0709-fusion.md", "docs/requirements/issue-0709-fusion.md"),
        ] {
            assert_eq!(to_root_relative(shard), root, "{shard} assembles to {root}");
            assert_eq!(to_shard_relative(root), shard, "{root} shards to {shard}");
        }
    }

    #[test]
    fn a_link_to_the_shard_directory_itself_stays_a_link() {
        assert_eq!(to_shard_relative(SHARDS), ".");
    }

    #[test]
    fn a_link_that_means_the_same_thing_everywhere_is_left_alone() {
        for target in [
            "https://example.org/a.md",
            "#an-anchor",
            "/docs/absolute.md",
            "mailto:someone@example.org",
        ] {
            assert_eq!(to_root_relative(target), target);
            assert_eq!(to_shard_relative(target), target);
        }
    }

    #[test]
    fn rewriting_touches_the_target_and_nothing_else() {
        let shard = "See [`docs/upload-memory.md`](../upload-memory.md) and \
                     [the spec](https://example.org) (a note) — cost: $1 (approx).\n";
        let root = "See [`docs/upload-memory.md`](docs/upload-memory.md) and \
                    [the spec](https://example.org) (a note) — cost: $1 (approx).\n";
        assert_eq!(rewrite_links(shard, &to_root_relative), root);
        assert_eq!(rewrite_links(root, &to_shard_relative), shard);
    }

    #[test]
    fn a_link_title_survives_rewriting() {
        assert_eq!(
            rewrite_links("[a](../b.md \"Title\")", &to_root_relative),
            "[a](docs/b.md \"Title\")"
        );
    }

    #[test]
    fn a_shard_link_that_resolves_only_from_the_repository_root_fails() {
        let shards = [PathBuf::from("docs/requirements/issue-0018-memory.md")];
        let read = |_path: &Path| "## Issue #18\n\nSee [it](docs/upload-memory.md).\n".to_string();
        let exists = |path: &Path| path == Path::new("docs/upload-memory.md");
        let failures = link_violations(&shards, &read, &exists);
        assert_eq!(failures.len(), 1, "{failures:?}");
        assert!(failures[0].contains("docs/upload-memory.md"), "{failures:?}");
    }

    #[test]
    fn a_shard_link_that_resolves_from_the_shard_passes() {
        let shards = [PathBuf::from("docs/requirements/issue-0018-memory.md")];
        let read = |_path: &Path| "## Issue #18\n\nSee [it](../upload-memory.md#top).\n".to_string();
        let exists = |path: &Path| path == Path::new("docs/requirements/../upload-memory.md");
        assert!(link_violations(&shards, &read, &exists).is_empty());
    }

    #[test]
    fn a_shard_named_for_the_wrong_issue_fails() {
        let shards = [PathBuf::from("docs/requirements/issue-0991-copy.md")];
        let read = |_path: &Path| "## Issue #709 Multi-Source Search Fusion\n".to_string();
        let failures = shard_violations(&shards, &read);
        assert!(
            failures.iter().any(|failure| failure.contains("issue-0709-")),
            "{failures:?}"
        );
    }

    #[test]
    fn a_shard_named_for_its_own_issue_passes() {
        let shards = [PathBuf::from("docs/requirements/issue-0709-fusion.md")];
        let read = |_path: &Path| "## Issue #709 Multi-Source Search Fusion\n".to_string();
        assert!(shard_violations(&shards, &read).is_empty());
    }
}
