#!/usr/bin/env rust-script
//! Issue #954 (E102): the generated "Module map" section of ARCHITECTURE.md.
//!
//! One row per `pub mod` declared in `rust/src/lib.rs`: the module name,
//! a one-sentence responsibility (the module file's own `//!` first line,
//! with an override table for the modules whose file starts with code),
//! and the ARCHITECTURE.md section that owns it.
//!
//! Usage:
//!   rust-script scripts/generate-module-map.rs            # print the section
//!   rust-script scripts/generate-module-map.rs --check     # pin: the
//!           ARCHITECTURE.md module list equals lib.rs's mod list
//!   rust-script scripts/generate-module-map.rs --write     # replace the
//!           section between the markers in ARCHITECTURE.md
//!
//! The pinned property is coverage, not prose: `--check` (and the
//! `issue_954_module_map` unit test, which reads the same files) fails when
//! a module is declared in lib.rs but missing from the map, or when a map
//! row names a module that no longer exists -- so a new module fails CI
//! until documented, exactly as the issue requires.
//!
//! ```cargo
//! [package]
//! edition = "2024"
//! ```

use std::fs;
use std::path::{Path, PathBuf};

const LIB: &str = "rust/src/lib.rs";
const ARCHITECTURE: &str = "ARCHITECTURE.md";
const BEGIN: &str = "<!-- module-map:begin (generated by scripts/generate-module-map.rs) -->";
const END: &str = "<!-- module-map:end -->";

/// `relative` under the repository root: the working directory when the
/// script runs from the root, else the script's own checkout (the
/// `rust-script --test` harness runs tests from its cache directory).
fn repo_path(relative: &str) -> PathBuf {
    let direct = PathBuf::from(relative);
    if direct.exists() {
        return direct;
    }
    Path::new(file!())
        .parent()
        .and_then(Path::parent)
        .map(|root| root.join(relative))
        .unwrap_or(direct)
}

/// Modules whose file opens with code, not a doc comment. The sentence is
/// kept here so the map stays complete; when the module gains a real `//!`
/// header, the override can go.
const OVERRIDES: &[(&str, &str)] = &[
    (
        "agent",
        "Agent loop that plans, calls tools and records evidence",
    ),
    ("anthropic", "Anthropic API adapter for live engine calls"),
    (
        "arithmetic",
        "Exact and rounded arithmetic over Links Notation numbers",
    ),
    (
        "client_integrations",
        "Discovers and drives external client CLIs found on the host",
    ),
    (
        "concepts",
        "Concept records and lookup used across formalization",
    ),
    (
        "context_capacity",
        "Measures and enforces the context-window budget for prompts",
    ),
    (
        "definition_merge",
        "Merges concept definitions from seeds, memory and fresh evidence",
    ),
    (
        "engine",
        "Engine entry: formalize, solve, and compose the answer",
    ),
    ("gemini", "Gemini API adapter for live engine calls"),
    (
        "github_logs",
        "Collects issue, pull-request and CI logs from GitHub as evidence",
    ),
    ("memory", "Doublet memory read/write over .lino backups"),
    ("needs", "Need records that gate solver retries"),
    (
        "protocol",
        "The engine request/response protocol shared by every surface",
    ),
    (
        "proxy",
        "TCP proxy that records and replays engine traffic for tests",
    ),
    ("seed", "Seed knowledge loaded from data/seed/*.lino"),
    (
        "server",
        "The long-running engine server answering protocol requests",
    ),
    (
        "shared_memory",
        "The on-disk memory file contract and its locking rules",
    ),
    ("solver", "The universal problem solver dispatch and search"),
    (
        "telegram",
        "Telegram bot surface: prompt composition and reply formatting",
    ),
    (
        "telegram_runtime",
        "Long-poll runtime that keeps the Telegram surface alive",
    ),
];

/// The ordered rules assigning each module its owning doc section. Each
/// rule is a needle list, a section number, and whether the needle must be
/// a name prefix (true) or may appear anywhere in it (false). First match
/// wins; a module nothing claims stays in §2, the pipeline overview.
const SECTION_RULES: &[(&[&str], &str, bool)] = &[
    (
        &["solver", "method_registry", "meta_method_dispatch"],
        "7",
        true,
    ),
    (
        &[
            "retrieval",
            "route_method",
            "handler_promotion",
            "method_learning",
            "repair_strategy",
            "capability_routing",
        ],
        "7",
        false,
    ),
    (
        &[
            "world_model",
            "dreaming",
            "knowledge",
            "formal_system",
            "es_meta",
            "es_tokenizer",
            "grammar_kinds",
        ],
        "5",
        true,
    ),
    (&["meta_"], "5", true),
    (&["relative_meta_logic"], "5", true),
    (
        &[
            "algorithm_discovery",
            "proof_engine",
            "proof_program",
            "family_method",
            "reasoning_standard",
            "concept_lookup",
            "entity_resolution",
            "definition_merge",
            "prerequisite",
        ],
        "5",
        true,
    ),
    (
        &["translate", "language", "lexeme_import", "multilingual"],
        "10",
        false,
    ),
    (
        &[
            "memory",
            "doublet",
            "ledger",
            "seed",
            "link_store",
            "storage_policy",
            "shared_memory",
        ],
        "4",
        false,
    ),
    (
        &["temperature", "probability", "evidence", "selection"],
        "6.1",
        false,
    ),
    (
        &[
            "nested",
            "step",
            "plan",
            "task",
            "recursive_execution",
            "orchestration",
            "anticipation",
            "thinking",
            "self_explanation",
            "dialog_conversation",
            "conversation_context",
            "shared_dialog",
            "context_capacity",
        ],
        "8",
        false,
    ),
    (
        &["rule", "substitution", "transformation", "links_query"],
        "9",
        false,
    ),
    (&["config", "environment"], "11", true),
    (
        &[
            "event_log",
            "dialog_log",
            "trace_record",
            "release_timeline",
            "how_to_capture_manifest",
            "authoring_loop",
            "learning_cycle",
        ],
        "12",
        false,
    ),
    (
        &[
            "github",
            "issue_report",
            "contribution",
            "repository_workspace",
            "workspace_change_learning",
            "self_source_links",
        ],
        "14",
        true,
    ),
    (
        &[
            "test",
            "harness",
            "handcheck",
            "benchmark",
            "self_ast_census",
            "statement_audit",
            "statement_verification",
            "fact_checking",
        ],
        "15",
        false,
    ),
    (
        &[
            "web",
            "desktop",
            "cli_",
            "mcp",
            "proxy",
            "client_",
            "server",
            "protocol",
            "telegram",
            "computer_use",
            "local_transport",
            "service_accessibility",
            "source_fetch",
            "document_formats",
            "attachment_context",
            "summarization",
        ],
        "13",
        true,
    ),
    (
        &[
            "intent",
            "formaliz",
            "meaning",
            "composition",
            "cst",
            "catalog",
            "coding",
            "json_lino",
            "sequences",
            "normal_markov",
            "option_network",
            "cue_lexicon",
            "procedure",
            "skill",
            "program_skill",
            "how_to",
            "recipe",
            "question",
            "research",
            "source_",
            "search",
            "tool_scope",
            "promotion",
            "execution_box",
            "behavior_delta",
            "bounded_autonomy",
            "change_request",
            "draft_portfolio",
            "box_language",
            "implementation_language",
            "rust_projection",
            "associative",
            "concept_sense",
            "google_trends",
            "external",
        ],
        "3",
        false,
    ),
];

struct Row {
    name: String,
    responsibility: String,
    section: String,
}

fn section_for(name: &str) -> &'static str {
    for (needles, section, prefix) in SECTION_RULES {
        for needle in *needles {
            let hit = if *prefix {
                name.starts_with(needle)
            } else {
                name.contains(needle)
            };
            if hit {
                return section;
            }
        }
    }
    "2"
}

/// The module's own `//!` first line, or its `/* … */` header's opening
/// sentence for the files that start with a block comment.
fn header_doc(name: &str) -> Option<String> {
    for candidate in [
        format!("rust/src/{name}.rs"),
        format!("rust/src/{name}/mod.rs"),
    ] {
        let Ok(source) = fs::read_to_string(repo_path(&candidate)) else {
            continue;
        };
        let mut first = String::new();
        for line in source.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            if let Some(rest) = trimmed.strip_prefix("//!") {
                let rest = rest.trim();
                if !rest.is_empty() && first.is_empty() {
                    first = rest.to_string();
                }
                break;
            }
            if trimmed.starts_with("/*") || trimmed.starts_with('*') {
                let body = trimmed
                    .trim_start_matches("/*")
                    .trim_end_matches("*/")
                    .trim();
                if !body.is_empty() {
                    first = format!("{first}{body}");
                }
                if trimmed.ends_with("*/") {
                    break;
                }
                continue;
            }
            if trimmed.starts_with("//") {
                continue;
            }
            break;
        }
        if !first.is_empty() {
            return Some(first);
        }
        return None;
    }
    None
}

fn tidy(source: &str) -> String {
    let mut doc: String = source.split_whitespace().collect::<Vec<_>>().join(" ");
    while doc.ends_with('.') {
        doc.pop();
        doc = doc.trim_end().to_string();
    }
    if doc.chars().count() > 108 {
        doc = doc.chars().take(105).collect::<String>();
        if let Some(cut) = doc.rfind(' ') {
            doc.truncate(cut);
        }
    }
    for tail in [
        " and", " the", " of", " to", " a", " an", " in", " for", " with", " by", " —", "—",
        "*how*",
    ] {
        if doc.ends_with(tail) {
            doc.truncate(doc.len() - tail.len());
            doc = doc.trim_end().to_string();
        }
    }
    format!("{doc}.")
}

fn rows() -> Vec<Row> {
    let lib = fs::read_to_string(repo_path(LIB)).expect("rust/src/lib.rs readable");
    let mut rows = Vec::new();
    for line in lib.lines() {
        let Some(name) = line
            .strip_prefix("pub mod ")
            .and_then(|rest| rest.strip_suffix(';'))
        else {
            continue;
        };
        let responsibility = OVERRIDES
            .iter()
            .find(|(candidate, _)| *candidate == name)
            .map(|(_, sentence)| sentence.to_string())
            .or_else(|| header_doc(name))
            .unwrap_or_default();
        rows.push(Row {
            name: name.to_string(),
            responsibility: tidy(&responsibility),
            section: section_for(name).to_string(),
        });
    }
    rows.sort_by(|left, right| {
        left.section
            .parse::<f32>()
            .unwrap_or(2.0)
            .partial_cmp(&right.section.parse::<f32>().unwrap_or(2.0))
            .unwrap()
            .then_with(|| left.name.cmp(&right.name))
    });
    rows
}

fn rendered() -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str("One row per module declared in `rust/src/lib.rs`. Regenerate with\n");
    out.push_str("`rust-script scripts/generate-module-map.rs --write`; the module list is\n");
    out.push_str("pinned by `rust/tests/unit/issue_954_module_map.rs` (and `--check`), so a\n");
    out.push_str("new module fails CI until this map documents it.\n\n");
    out.push_str("| Module | Responsibility | Owning section |\n");
    out.push_str("|---|---|---|\n");
    for row in rows() {
        out.push_str(&format!(
            "| `{}` | {} | §{} |\n",
            row.name, row.responsibility, row.section
        ));
    }
    out.push_str(END);
    out
}

/// The map's first column, read back out of a rendered section: every line
/// shaped like a table row whose first cell is a bare `` `name` ``.
fn mapped_names(section: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in section.lines() {
        let rest = line.trim().strip_prefix('|').map(|rest| rest.trim());
        let Some(rest) = rest else { continue };
        if rest.starts_with("---") || rest.starts_with("Module |") {
            continue;
        }
        let Some((name, _)) = rest.split_once('|') else {
            continue;
        };
        let name = name.trim().trim_matches('`');
        if !name.is_empty()
            && name
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '_')
        {
            names.push(name.to_string());
        }
    }
    names
}

/// The generated section currently inside ARCHITECTURE.md, markers
/// included; the pin compares its name column against lib.rs.
fn committed_section(architecture: &str) -> String {
    let begin = architecture
        .find(BEGIN)
        .unwrap_or_else(|| panic!("{ARCHITECTURE} carries the module-map begin marker"));
    let end = architecture
        .find(END)
        .unwrap_or_else(|| panic!("{ARCHITECTURE} carries the module-map end marker"));
    architecture[begin..end + END.len()].to_string()
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let check = args.iter().any(|argument| argument == "--check");
    let write = args.iter().any(|argument| argument == "--write");

    let architecture =
        fs::read_to_string(repo_path(ARCHITECTURE)).expect("ARCHITECTURE.md readable");
    let section = committed_section(&architecture);

    if check {
        let declared: Vec<String> = rows().into_iter().map(|row| row.name).collect();
        let mapped = mapped_names(&section);
        let missing: Vec<&String> = declared
            .iter()
            .filter(|name| !mapped.contains(name))
            .collect();
        let stale: Vec<&String> = mapped
            .iter()
            .filter(|name| !declared.contains(name))
            .collect();
        if !missing.is_empty() || !stale.is_empty() {
            eprintln!(
                "generate-module-map: the ARCHITECTURE.md module map is out of sync with {LIB} -- missing {:?}, stale {:?}; run --write",
                missing, stale
            );
            std::process::exit(1);
        }
        println!("module map covers all {} declared modules", declared.len());
        return;
    }

    if write {
        let updated = format!(
            "{}{}{}",
            &architecture[..architecture.find(BEGIN).expect("begin marker")],
            rendered(),
            &architecture[architecture.find(END).expect("end marker") + END.len()..]
        );
        fs::write(ARCHITECTURE, updated).expect("ARCHITECTURE.md writable");
        println!("rewrote the module map section in {ARCHITECTURE}");
        return;
    }

    print!("{}", rendered());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_map_covers_every_declared_module_with_a_sentence() {
        let all = rows();
        assert!(all.len() >= 150, "lib.rs declares {} modules", all.len());
        assert!(
            all.iter().all(|row| !row.responsibility.is_empty()),
            "every module carries a one-sentence responsibility"
        );
    }

    #[test]
    fn the_owning_sections_are_the_documents_own_numbers() {
        for row in rows() {
            let number: f32 = row.section.parse().expect("a section number");
            assert!(
                (2.0..=15.0).contains(&number),
                "{} -> {}",
                row.name,
                row.section
            );
        }
    }

    #[test]
    fn tidy_truncates_without_dangling_words() {
        let sentence = tidy(
            "rethinking *how* to solve the general failure-to-repair classifier when the meta algorithm and the",
        );
        assert!(sentence.chars().count() < 120);
        assert!(!sentence.ends_with(" and"));
        assert!(sentence.ends_with('.'));
    }

    #[test]
    fn mapped_names_reads_the_first_column_back() {
        let names = mapped_names(
            "| Module | Responsibility | Owning section |\n|---|---|---|\n| `solver` | The universal problem solver. | §7 |\n| not a row\n",
        );
        assert_eq!(names, vec!["solver".to_string()]);
    }
}
