// Generated by `node scripts/generate-worker-crate-modules.mjs --write`
// from js/agentic/crate/links_format.mjs.
// Do not edit by hand: edit that module and regenerate. The browser worker
// cannot import ES modules, so the module is a factory that
// formal_ai_worker_crate_modules.js runs on first use.

(self.FORMAL_AI_CRATE_FACTORIES ||= {})["crate/links_format.mjs"] = (crateRequire) => {
// Compact Links Notation records (rust/src/links_format.rs), with the
// `lino_objects_codec::format` quoting they borrow
// (lino-objects-codec 0.7.0 `format_indented_ordered`, `escape_reference`,
// `format_indented_value`).

/** Rust dependency `lino_objects_codec::format::escape_reference`. @param {string} value */
function escapeReference(value) {
  const needsEscaping = /[\s()'":]/u.test(value) || value.includes('\n');
  if (!needsEscaping) return value;
  const hasSingle = value.includes("'");
  const hasDouble = value.includes('"');
  if (hasSingle && !hasDouble) return `"${value}"`;
  if (hasDouble && !hasSingle) return `'${value}'`;
  if (hasSingle && hasDouble) {
    const singleCount = value.split("'").length - 1;
    const doubleCount = value.split('"').length - 1;
    if (doubleCount < singleCount) return `"${value.replaceAll('"', '""')}"`;
    return `'${value.replaceAll("'", "''")}'`;
  }
  return `'${value}'`;
}

/** Mirrors `fn format_indented_value` in lino-objects-codec `format`. @param {string} value */
function formatIndentedValue(value) {
  const hasSingle = value.includes("'");
  const hasDouble = value.includes('"');
  if (hasDouble && !hasSingle) return `'${value}'`;
  if (hasSingle && !hasDouble) return `"${value}"`;
  if (hasSingle && hasDouble) return `'${value.replaceAll("'", "''")}'`;
  return `"${value}"`;
}

/**
 * Rust dependency `lino_objects_codec::format::format_indented_ordered`.
 * @param {string} id
 * @param {Array<[string, string]>} pairs
 * @param {string} indent
 */
function formatIndentedOrdered(id, pairs, indent) {
  if (!id) throw new Error('format_indented_ordered: missing id');
  const lines = [id];
  for (const [key, value] of pairs) lines.push(`${indent}${escapeReference(key)} ${formatIndentedValue(value)}`);
  return lines.join('\n');
}

/**
 * Mirrors `fn format_lino_record` in rust/src/links_format.rs.
 * @param {string} id
 * @param {Array<[string, string]>} pairs
 */
function formatLinoRecord(id, pairs) {
  return formatIndentedOrdered(id, pairs.map(([key, value]) => [key, sanitizeLinoValue(value)]), '  ');
}

/** Mirrors `fn format_lino_value_verbatim`. @param {string} value */
function formatLinoValueVerbatim(value) {
  return formatIndentedValue(value);
}

/** Mirrors `fn format_lino_value`. @param {string} value */
function formatLinoValue(value) {
  return formatLinoValueVerbatim(sanitizeLinoValue(value));
}

/**
 * Mirrors `fn push_lino_node`: returns `out` with one `name "value"` line appended.
 * @param {string} out
 * @param {number} indent
 * @param {string} name
 * @param {string|null} value
 */
function pushLinoNode(out, indent, name, value) {
  return `${out}${' '.repeat(indent)}${name}${value === null || value === undefined ? '' : ` ${formatLinoValue(value)}`}\n`;
}

/**
 * Mirrors `fn push_lino_field`: returns `out` with one `name value` line appended.
 * @param {string} out
 * @param {number} indent
 * @param {string} name
 * @param {string|null} value
 */
function pushLinoField(out, indent, name, value) {
  return `${out}${' '.repeat(indent)}${name}${value === null || value === undefined ? '' : ` ${value}`}\n`;
}

/** Mirrors `fn sanitize_lino_value`. @param {string} value */
function sanitizeLinoValue(value) {
  return value.replaceAll('\\', '\\\\').replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\t', '\\t');
}

/** Mirrors `fn flatten_lino_value`. @param {string} value */
function flattenLinoValue(value) {
  return value.replaceAll('\r', '\\r').replaceAll('\n', '\\n').replaceAll('\t', '\\t');
}

return Object.freeze({
  escapeReference,
  formatIndentedOrdered,
  formatLinoRecord,
  formatLinoValueVerbatim,
  formatLinoValue,
  pushLinoNode,
  pushLinoField,
  sanitizeLinoValue,
  flattenLinoValue,
});
};
