// Generated by `node scripts/generate-worker-crate-modules.mjs --write`
// from js/agentic/crate/literal_instruction_view.mjs.
// Do not edit by hand: edit that module and regenerate. The browser worker
// cannot import ES modules, so the module is a factory that
// formal_ai_worker_crate_modules.js runs on first use.

(self.FORMAL_AI_CRATE_FACTORIES ||= {})["crate/literal_instruction_view.mjs"] = (crateRequire) => {
/** Mirrors `fn instruction_view`: a cycle-free source-position projection. */
function literalInstructionView(request, payload) {
  if (payload === null) return request;
  const { start, end } = payload;
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || start > end || end > request.length) return null;
  return request.slice(0, start) + ' '.repeat(end - start) + request.slice(end);
}

return Object.freeze({
  literalInstructionView,
});
};
