// Generated by `node scripts/generate-worker-crate-modules.mjs --write`
// from js/agentic/crate/seed_parser.mjs.
// Do not edit by hand: edit that module and regenerate. The browser worker
// cannot import ES modules, so the module is a factory that
// formal_ai_worker_crate_modules.js runs on first use.

(self.FORMAL_AI_CRATE_FACTORIES ||= {})["crate/seed_parser.mjs"] = (crateRequire) => {
// `crate::seed::parser::parse_lino` root shape.
//
// The Rust parser always returns a synthetic, unnamed root whose children are
// the document's top-level nodes; the shared JavaScript parser collapses a
// document with a single top-level node onto that node. `parseRoot` restores
// the Rust shape so `tree.children.first()` reads the same node in both.

const { parseLino } = crateRequire("host.mjs");

/** Mirrors `parse_lino`: always the unnamed root. @param {string} text */
function parseRoot(text) {
  const tree = parseLino(text);
  if (tree.indent === -1 || (tree.name === '' && tree.value === '' && tree.indent === undefined)) return tree;
  return { name: '', id: '', value: '', children: [tree], indent: -1 };
}

/** Mirrors `LinoNode::find_child_value`. */
function findChildValue(node, name) {
  return (node?.children || []).find((child) => child.name === name)?.value ?? '';
}

return Object.freeze({
  parseRoot,
  findChildValue,
});
};
