// Generated by `node scripts/generate-worker-crate-modules.mjs --write`
// from js/agentic/crate/summarization_identifier.mjs.
// Do not edit by hand: edit that module and regenerate. The browser worker
// cannot import ES modules, so the module is a factory that
// formal_ai_worker_crate_modules.js runs on first use.

(self.FORMAL_AI_CRATE_FACTORIES ||= {})["crate/summarization_identifier.mjs"] = (crateRequire) => {
// `crate::summarization::identifier` (rust/src/summarization/identifier.rs):
// the identifier rung, one step shorter than a topic label. A `NamingConvention`
// is its string label; an `IdentifierBudget` is `{max_length, max_words}`.

const { functionWords, isReservedWord, stripWords, tokenize } = crateRequire("crate/summarization_vocabulary.mjs");

/** Mirrors `DEFAULT_IDENTIFIER_MAX_LENGTH` in rust/src/summarization/identifier.rs. */
const DEFAULT_IDENTIFIER_MAX_LENGTH = 40;
/** Mirrors `DEFAULT_IDENTIFIER_MAX_WORDS` in rust/src/summarization/identifier.rs. */
const DEFAULT_IDENTIFIER_MAX_WORDS = 4;

/** Mirrors `enum NamingConvention` in rust/src/summarization/identifier.rs. */
const NamingConvention = Object.freeze({
  SnakeCase: 'snake_case',
  ScreamingSnakeCase: 'screaming_snake_case',
  CamelCase: 'camel_case',
  PascalCase: 'pascal_case',
  CommitSubject: 'commit_subject',
});

/** Mirrors `NamingConvention::is_code` in rust/src/summarization/identifier.rs. */
function isCode(convention) {
  return convention !== NamingConvention.CommitSubject;
}

/**
 * Mirrors `IdentifierBudget::default` / `IdentifierBudget::new` in
 * rust/src/summarization/identifier.rs.
 * @param {number} [maxLength]
 * @param {number} [maxWords]
 * @returns {{max_length: number, max_words: number}}
 */
function identifierBudget(maxLength = DEFAULT_IDENTIFIER_MAX_LENGTH, maxWords = DEFAULT_IDENTIFIER_MAX_WORDS) {
  return { max_length: maxLength, max_words: maxWords };
}

/** Mirrors `IdentifierBudget::commit_subject` in rust/src/summarization/identifier.rs. */
function commitSubjectBudget() {
  return { max_length: 50, max_words: 10 };
}

/** Mirrors `IdentifierBudget::admits` in rust/src/summarization/identifier.rs. */
function budgetAdmits(budget, candidate) {
  return candidate !== '' && Array.from(candidate).length <= budget.max_length;
}

const UPPERCASE = /^\p{Uppercase}$/u;
const LOWERCASE = /^\p{Lowercase}$/u;
const ALPHABETIC = /^\p{Alphabetic}$/u;
const NUMERIC = /^\p{N}$/u;

/** Mirrors `fn capitalize` in rust/src/summarization/identifier.rs. */
function capitalize(word) {
  const chars = Array.from(word);
  if (chars.length === 0) return '';
  return chars[0].toUpperCase() + chars.slice(1).join('');
}

/** Mirrors `fn render` in rust/src/summarization/identifier.rs. */
function render(words, convention) {
  switch (convention) {
    case NamingConvention.SnakeCase: return words.join('_');
    case NamingConvention.ScreamingSnakeCase: return words.join('_').toUpperCase();
    case NamingConvention.CamelCase:
      return words.map((word, index) => (index === 0 ? word : capitalize(word))).join('');
    case NamingConvention.PascalCase: return words.map(capitalize).join('');
    default: return capitalize(words.join(' '));
  }
}

/** Mirrors `fn polish` in rust/src/summarization/identifier.rs. */
function polish(candidate, convention) {
  if (!isCode(convention)) return candidate.replace(/^\p{White_Space}+|\p{White_Space}+$/gu, '');
  let out = candidate;
  const first = Array.from(out)[0];
  if (first !== undefined && NUMERIC.test(first)) out = `_${out}`;
  if (isReservedWord(out)) out = `${out}_`;
  return out;
}

/** Mirrors `fn clip` in rust/src/summarization/identifier.rs. */
function clip(candidate, max) {
  const chars = Array.from(candidate).slice(0, max);
  while (chars.length > 0 && (chars[chars.length - 1] === '_' || chars[chars.length - 1] === ' ')) chars.pop();
  return chars.join('');
}

/** Mirrors `fn assemble` in rust/src/summarization/identifier.rs. */
function assemble(words, convention, budget) {
  let count = Math.min(words.length, Math.max(budget.max_words, 1));
  for (;;) {
    const candidate = polish(render(words.slice(0, count), convention), convention);
    if (budgetAdmits(budget, candidate) || count <= 1) {
      if (budgetAdmits(budget, candidate)) return candidate;
      const cut = polish(clip(candidate, budget.max_length), convention);
      if (budgetAdmits(budget, cut) || budget.max_length === 0) return cut;
      return polish(clip(candidate, Math.max(0, budget.max_length - 1)), convention);
    }
    count -= 1;
  }
}

/**
 * Mirrors `fn to_identifier` in rust/src/summarization/identifier.rs: `text`
 * shortened to one name in `convention` within `budget` (function words dropped,
 * the word list capped, keyword collisions and leading digits escaped).
 * @param {string} text
 * @param {string} convention a `NamingConvention`
 * @param {{max_length: number, max_words: number}} budget
 */
function toIdentifier(text, convention, budget) {
  const tokens = tokenize(text);
  if (tokens.length === 0) return '';
  let words = stripWords(tokens, functionWords());
  if (words.length === 0) words = tokens;
  if (isCode(convention)) {
    words = words.map((word) => word.split("'").join('')).filter((word) => word !== '');
  }
  if (words.length === 0) return '';
  return assemble(words, convention, budget);
}

/**
 * Mirrors `fn is_valid_identifier` in rust/src/summarization/identifier.rs.
 * @param {string} candidate
 * @param {string} convention a `NamingConvention`
 */
function isValidIdentifier(candidate, convention) {
  if (candidate === '') return false;
  if (convention === NamingConvention.CommitSubject) {
    return !candidate.includes('\n') && !candidate.endsWith('.')
      && candidate.replace(/^\p{White_Space}+|\p{White_Space}+$/gu, '') === candidate;
  }
  const chars = Array.from(candidate);
  const first = chars[0];
  if (!(ALPHABETIC.test(first) || first === '_')) return false;
  if (!chars.every((character) => ALPHABETIC.test(character) || NUMERIC.test(character) || character === '_')) return false;
  if (isReservedWord(candidate)) return false;
  const core = candidate.replace(/^_+|_+$/g, '');
  if (core === '') return false;
  const coreChars = Array.from(core);
  switch (convention) {
    case NamingConvention.SnakeCase: return !coreChars.some((character) => UPPERCASE.test(character));
    case NamingConvention.ScreamingSnakeCase: return !coreChars.some((character) => LOWERCASE.test(character));
    case NamingConvention.CamelCase: return !core.includes('_') && !UPPERCASE.test(coreChars[0]);
    case NamingConvention.PascalCase: return !core.includes('_') && !LOWERCASE.test(coreChars[0]);
    default: return true;
  }
}

return Object.freeze({
  DEFAULT_IDENTIFIER_MAX_LENGTH,
  DEFAULT_IDENTIFIER_MAX_WORDS,
  NamingConvention,
  isCode,
  identifierBudget,
  commitSubjectBudget,
  budgetAdmits,
  toIdentifier,
  isValidIdentifier,
});
};
