// Generated by `node scripts/generate-worker-crate-modules.mjs --write`
// from js/agentic/content.mjs.
// Do not edit by hand: edit that module and regenerate. The browser worker
// cannot import ES modules, so the module is a factory that
// formal_ai_worker_crate_modules.js runs on first use.

(self.FORMAL_AI_CRATE_FACTORIES ||= {})["content.mjs"] = (crateRequire) => {
// The chat-message readers the planner shares (rust/src/protocol/content.rs,
// rust/src/protocol.rs `ChatMessage`).
//
// Messages are the parsed shape of js/server/chat-request.mjs
// `parseChatMessage`: `{role, content, tool_calls, tool_call_id, name,
// is_error}`, where `content` is a string or an array of `{type, text}` parts.

const { cached, childrenNamed, isDirectory, parseLino, readText } = crateRequire("host.mjs");

/** `MessageContent::plain_text`. */
function plainText(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content.filter((part) => typeof part?.text === 'string').map((part) => part.text).join('\n');
}

function injectedBlocks() {
  return cached('caller-context-blocks', () => {
    const root = parseLino(readText('data/seed/caller-context.lino'));
    const group = childrenNamed(root, 'injected_blocks')[0];
    return childrenNamed(group, 'block').map((block) => block.value);
  });
}

function stripBlock(text, open, close) {
  let remaining = text;
  let request = '';
  for (let start = remaining.indexOf(open); start >= 0; start = remaining.indexOf(open)) {
    request += remaining.slice(0, start);
    const afterOpen = remaining.slice(start + open.length);
    const end = afterOpen.indexOf(close);
    if (end < 0) {
      remaining = '';
      break;
    }
    remaining = afterOpen.slice(end + close.length);
  }
  return request + remaining;
}

/** `MessageContent::user_request_text`. */
function userRequestText(content) {
  return injectedBlocks()
    .reduce((text, tag) => stripBlock(text, `<${tag}>`, `</${tag}>`), plainText(content))
    .trim();
}

const utf8Length = (text) => new TextEncoder().encode(text).length;

/** `strip_system_echo`. */
function stripSystemEcho(request, system) {
  const MIN_ECHO = 40;
  if (!system.trim()) return request;
  const lines = rustLines(request);
  for (let start = 1; start < lines.length; start += 1) {
    const tail = lines.slice(start).join('\n').trim();
    if (utf8Length(tail) < MIN_ECHO || !system.includes(tail)) continue;
    const head = lines.slice(0, start).join('\n').trim();
    if (head) return head;
  }
  return request;
}

/**
 * `str::lines`: split on `\n`, drop one trailing `\r` per line, and no final
 * empty line after a trailing newline.
 * Rust built-in `str::lines`.
 * @param {string} text
 * @returns {Array<string>}
 */
function rustLines(text) {
  if (text === '') return [];
  const parts = text.split('\n');
  if (parts[parts.length - 1] === '') parts.pop();
  return parts.map((line) => (line.endsWith('\r') ? line.slice(0, -1) : line));
}

/** `system_prompt_text`. */
function systemPromptText(messages) {
  return messages
    .filter((message) => message.role.toLowerCase() === 'system')
    .map((message) => plainText(message.content))
    .join('\n');
}

/** `latest_user_request`: the latest user turn, decorations stripped, or null. */
function latestUserRequest(messages) {
  const system = systemPromptText(messages);
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message.role.toLowerCase() === 'user') {
      return stripSystemEcho(userRequestText(message.content), system);
    }
  }
  return null;
}

const isAbsolute = (path) => path.startsWith('/');

function fileNameOf(path) {
  const trimmed = path.replace(/\/+$/, '');
  const last = trimmed.split('/').pop();
  return last && last !== '..' && last !== '.' ? last : null;
}

/** `observed_directory`. */
function observedDirectory(messages) {
  const planned = [];
  for (const message of messages) {
    for (const call of message.tool_calls || []) {
      let value;
      try {
        value = JSON.parse(call.function.arguments);
      } catch {
        continue;
      }
      if (!value || typeof value !== 'object' || Array.isArray(value)) continue;
      for (const field of Object.keys(value).sort().map((key) => value[key])) {
        if (typeof field !== 'string') continue;
        if (!isAbsolute(field) && fileNameOf(field) !== null && !/[\n ]/.test(field)) planned.push(field);
      }
    }
  }
  if (!planned.length) return null;
  for (const message of messages) {
    if (message.role.toLowerCase() !== 'tool' || message.is_error) continue;
    for (const token of plainText(message.content).split(/[\s"'`,]/u)) {
      for (const relative of planned) {
        if (!token.endsWith(relative)) continue;
        const prefix = token.slice(0, token.length - relative.length);
        if (!prefix.endsWith('/')) continue;
        const root = prefix.slice(0, -1).replace(/\/+$/, '');
        if (root && isAbsolute(root)) return root;
      }
    }
  }
  return null;
}

function declaredDirectory(text) {
  const WORKSPACE_LIST = '**Workspace Directories:**';
  const tagged = text.split('<cwd>').slice(1).map((rest) => rest.split('</cwd>')[0]);
  const labelled = rustLines(text)
    .filter((line) => line.includes('Working directory:'))
    .map((line) => line.slice(line.indexOf('Working directory:') + 'Working directory:'.length));
  const listed = [];
  const at = text.indexOf(WORKSPACE_LIST);
  if (at >= 0) {
    for (const line of rustLines(text.slice(at + WORKSPACE_LIST.length)).slice(1)) {
      if (!line.trimStart().startsWith('- ')) break;
      listed.push(line.trimStart().slice(2));
    }
  }
  const declared = [...tagged, ...labelled, ...listed].map((path) => path.trim()).filter(isAbsolute);
  return declared.find((path) => isDirectory(path)) ?? declared[0] ?? null;
}

/** `client_working_directory`. */
function clientWorkingDirectory(messages) {
  const text = messages.map((message) => plainText(message.content)).join('\n');
  return declaredDirectory(text) ?? observedDirectory(messages);
}

/** `chat_message_to_turn`. */
function chatMessageToTurn(message) {
  const role = message.role.toLowerCase();
  const content = role === 'user' ? userRequestText(message.content) : plainText(message.content);
  if (!content.trim()) return null;
  if (role === 'user' || role === 'assistant') return { role, content };
  return null;
}

return Object.freeze({
  plainText,
  userRequestText,
  stripSystemEcho,
  rustLines,
  systemPromptText,
  latestUserRequest,
  observedDirectory,
  clientWorkingDirectory,
  chatMessageToTurn,
});
};
