// The coding catalog (rust/src/coding/catalog/mod.rs and its `languages`,
// `tasks`, `types` and `templates_*` tables). The tables are read from
// data/meta/agentic-coding-catalog.lino, generated byte-for-byte from the Rust
// constants, except the template programs, which come from the seed bundle
// data/seed/hello-world-programs.lino (or, for a row whose program_source is
// the documentation route, from the worker's rediscovery over the
// documentation captures, issue #1165); the alias surfaces come from the
// meaning lexicon, as in Rust.
//
// A language is `{slug, name, code_fence, execution: {check_command,
// run_command, notes}, source, save_as, framework_of}`; a task `{slug, label,
// output, input}`; a template `{task_slug, language_slug, code}`.

import { cached, childValue, childrenNamed, parseLino, readText, realm } from '../host.mjs';
import { meaningWords } from '../write_lexicon.mjs';
import { isAlphanumeric, isAsciiAlphanumeric, splitWhitespace } from '../write_str.mjs';

const CATALOG_FILE = 'data/meta/agentic-coding-catalog.lino';
const SEED_PROGRAMS_FILE = 'data/seed/hello-world-programs.lino';
/** The `program_source` of a template row whose program is rediscovered, not stored. */
const DOCUMENTATION_ROUTE = 'documentation_route';

/** Mirrors `const WRITE_PROGRAM_INTENT`. */
export const WRITE_PROGRAM_INTENT = 'write_program';

function optional(node, name) {
  const child = childrenNamed(node, name)[0];
  return child ? child.value : null;
}

/**
 * The program text of a catalog template, read from the seed bundle the Rust
 * catalog tests hold equal to the tables (`lino_seed_mirrors_every_catalog_template`),
 * so each program is stored once in data/ (issue #1165 R1165-8). Null when
 * the bundle has no row for the pair.
 */
function seedProgram(task, language) {
  const programs = cached('agentic-coding-catalog:seed-programs', () => {
    const byPair = new Map();
    for (const node of parseLino(readText(SEED_PROGRAMS_FILE)).children || []) {
      const code = optional(node, 'code');
      const key = `${optional(node, 'task')}:${optional(node, 'language')}`;
      if (code !== null) byPair.set(key, code);
      else if (optional(node, 'program_source') === DOCUMENTATION_ROUTE) byPair.set(key, DOCUMENTATION_ROUTE);
    }
    return byPair;
  });
  const program = programs.get(`${task}:${language}`) ?? null;
  // Issue #1165 R1165-4: a row whose program_source is the documentation
  // route stores no program; the worker realm rediscovers it from
  // data/seed/coding-documentation-captures.lino (writeProgramTemplate).
  if (program !== DOCUMENTATION_ROUTE) return program;
  return realm()?.writeProgramTemplate?.(task, language) ?? null;
}

function catalog() {
  return cached('agentic-coding-catalog', () => {
    const parsed = parseLino(readText(CATALOG_FILE));
    const root = childrenNamed(parsed, 'coding_catalog')[0] ?? parsed;
    return {
      languages: childrenNamed(root, 'language').map((node) => ({
        slug: node.value,
        name: childValue(node, 'name'),
        code_fence: childValue(node, 'code_fence'),
        execution: {
          check_command: optional(node, 'check_command'),
          run_command: childValue(node, 'run_command'),
          notes: childValue(node, 'notes'),
        },
        source: childValue(node, 'source'),
        save_as: childValue(node, 'save_as'),
        framework_of: optional(node, 'framework_of'),
      })),
      tasks: childrenNamed(root, 'task').map((node) => ({
        slug: node.value,
        label: childValue(node, 'label'),
        output: childValue(node, 'output'),
        input: childValue(node, 'input'),
      })),
      templates: childrenNamed(root, 'template').map((node) => {
        const task = childValue(node, 'task_slug');
        const language = childValue(node, 'language_slug');
        return { task_slug: task, language_slug: language, code: seedProgram(task, language) };
      }),
    };
  });
}

/** Mirrors `const PROGRAM_LANGUAGES`. */
export function programLanguages() {
  return catalog().languages;
}

/** Mirrors `const PROGRAM_TASKS`. */
export function programTasks() {
  return catalog().tasks;
}

/** Mirrors `fn program_templates`. */
export function programTemplates() {
  return catalog().templates;
}

/** Mirrors `fn program_language_by_slug`. */
export function programLanguageBySlug(slug) {
  return programLanguages().find((language) => language.slug === slug) ?? null;
}

/** Mirrors `fn program_task_by_slug`. */
export function programTaskBySlug(slug) {
  return programTasks().find((task) => task.slug === slug) ?? null;
}

/** Mirrors `fn program_template`. */
export function programTemplate(taskSlug, languageSlug) {
  return programTemplates().find((template) =>
    template.task_slug === taskSlug && template.language_slug === languageSlug) ?? null;
}

/**
 * The file a pair's program is saved as: the catalog row's, or the one the
 * documented run contract binds when the program declares another name
 * (issue #1165 R1165-6, HelloWorldApp.java). Mirrors
 * `program_spec(..).language.save_as`.
 */
export function programSaveAs(taskSlug, language) {
  return realm()?.writeProgramLanguageInfo?.(taskSlug, language.slug)?.saveAs ?? language.save_as;
}

/**
 * The check and run commands a pair's program is run with: the catalog row's,
 * or the ones the documented run contract binds (issue #1165 R1165-6).
 * Mirrors `program_spec(..).language.execution`.
 */
export function programExecution(taskSlug, language) {
  const bound = realm()?.writeProgramLanguageInfo?.(taskSlug, language.slug);
  if (!bound) return language.execution;
  return { ...language.execution, check_command: bound.checkCommand ?? null, run_command: bound.runCommand };
}

/** Mirrors `ProgramLanguage::is_framework`. */
export function isFramework(language) {
  return language.framework_of !== null;
}

/** Mirrors `ProgramLanguage::base_language`. */
export function baseLanguage(language) {
  return (language.framework_of !== null && programLanguageBySlug(language.framework_of)) || language;
}

function aliasSurfaces(prefix, slug) {
  return meaningWords(`${prefix}_${slug}`);
}

function namesTarget(normalized, language) {
  return aliasSurfaces('program_language', language.slug).some((alias) => containsToken(normalized, alias));
}

/** Mirrors `fn program_language_by_alias`. @param {string} normalized */
export function programLanguageByAlias(normalized) {
  const languages = programLanguages();
  return languages.find((language) => isFramework(language) && namesTarget(normalized, language))
    ?? languages.find((language) => namesTarget(normalized, language))
    ?? null;
}

/** Mirrors `fn composition_language`. */
export function compositionLanguage(normalized, inherited) {
  const language = programLanguageByAlias(normalized) ?? inherited;
  return language ? baseLanguage(language) : null;
}

/** Mirrors `fn program_task_by_alias`. @param {string} normalized */
export function programTaskByAlias(normalized) {
  return programTasks().find((task) =>
    aliasSurfaces('program_task', task.slug).some((alias) => containsPhrase(normalized, alias))) ?? null;
}

/** Mirrors `fn supported_program_languages`. */
export function supportedProgramLanguages() {
  return programLanguages().map((language) => language.slug).join(', ');
}

/** Mirrors `fn supported_program_tasks`. */
export function supportedProgramTasks() {
  return programTasks().map((task) => task.slug).join(', ');
}

/** Mirrors `fn contains_cjk`. @param {string} text */
export function containsCjk(text) {
  for (const character of text) {
    const cp = character.codePointAt(0);
    if ((cp >= 0x3400 && cp <= 0x4dbf) || (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0xf900 && cp <= 0xfaff)
      || (cp >= 0x3040 && cp <= 0x30ff) || (cp >= 0x3100 && cp <= 0x312f)) return true;
  }
  return false;
}

/** Mirrors `fn contains_devanagari`. @param {string} text */
export function containsDevanagari(text) {
  for (const character of text) {
    const cp = character.codePointAt(0);
    if (cp >= 0x0900 && cp <= 0x097f) return true;
  }
  return false;
}

function isAliasContinuation(character) {
  const spaceless = containsCjk(character) || containsDevanagari(character);
  return (isAlphanumeric(character) && !spaceless) || character === '+' || character === '#';
}

function containsToken(normalized, expected) {
  if (containsCjk(expected)) return normalized.includes(expected);
  if (Array.from(expected).every(isAsciiAlphanumeric)) {
    if (expected === '') return true;
    for (let index = normalized.indexOf(expected); index >= 0; index = normalized.indexOf(expected, index + expected.length)) {
      const before = Array.from(normalized.slice(0, index)).pop();
      const after = Array.from(normalized.slice(index + expected.length))[0];
      if ((before === undefined || !isAliasContinuation(before)) && (after === undefined || !isAliasContinuation(after))) {
        return true;
      }
    }
    return false;
  }
  return splitWhitespace(normalized).some((token) => token === expected);
}

function containsPhrase(normalized, expected) {
  if (containsCjk(expected)) return normalized.includes(expected);
  return normalized === expected
    || normalized.startsWith(`${expected} `)
    || normalized.endsWith(` ${expected}`)
    || normalized.includes(` ${expected} `);
}
