// Generated by `rust-script scripts/normalize-ordered-lists.rs --write`.
//
// The browser worker loads every module in `src/web/worker/`. Issue #991 moved
// this list out of `formal_ai_worker.js` so it can be union merged: two branches
// that each add a worker module now produce a superset instead of a conflict, and
// the generator above restores this exact content from the directory itself.

self.FORMAL_AI_WORKER_MODULES = Object.freeze([
  "worker/formal_ai_worker_00.js",
  "worker/formal_ai_worker_01.js",
  "worker/formal_ai_worker_02.js",
  "worker/formal_ai_worker_03.js",
  "worker/formal_ai_worker_04.js",
  "worker/formal_ai_worker_05.js",
  "worker/formal_ai_worker_06.js",
  "worker/formal_ai_worker_07.js",
  "worker/formal_ai_worker_08.js",
  "worker/formal_ai_worker_09.js",
  "worker/formal_ai_worker_10.js",
  "worker/formal_ai_worker_11.js",
  "worker/formal_ai_worker_12.js",
  "worker/formal_ai_worker_13.js",
  "worker/formal_ai_worker_14.js",
  "worker/formal_ai_worker_15.js",
  "worker/formal_ai_worker_16.js",
  "worker/formal_ai_worker_17.js",
  "worker/formal_ai_worker_18.js",
  "worker/formal_ai_worker_19.js",
  "worker/formal_ai_worker_20.js",
  "worker/formal_ai_worker_21.js",
  "worker/formal_ai_worker_22.js",
  "worker/formal_ai_worker_23.js",
  "worker/formal_ai_worker_24.js",
  "worker/formal_ai_worker_how_to_guide.js",
]);
