//! Regression coverage for issue #848's coding-task ladder.
//!
//! A passing response is not evidence of a code change. These tests inspect the
//! bytes that the real offline Agent CLI loop writes and then reads back.

use formal_ai::agentic_coding::{plan_chat_step, run_agentic_task, AgenticPlan};
use formal_ai::protocol::{ChatMessage, ToolCall};

const CREATE_RUST_FUNCTION: &str = "Create a new file src/si_units.rs in this repository \
    containing a single public Rust function millimetres_to_metres that takes an f64 and \
    returns it divided by 1000.0.";

#[test]
fn rust_function_request_writes_executable_source_and_observes_it() {
    let outcome = run_agentic_task(CREATE_RUST_FUNCTION).expect("isolated agent workspace");
    assert!(
        !outcome.hit_turn_cap,
        "agent loop must terminate: {outcome:?}"
    );

    let target = outcome
        .steps
        .iter()
        .find(|step| {
            if step.tool != "write_file" {
                return false;
            }
            serde_json::from_str::<serde_json::Value>(&step.arguments)
                .ok()
                .and_then(|arguments| arguments["path"].as_str().map(str::to_owned))
                .is_some_and(|path| path == "src/si_units.rs")
        })
        .unwrap_or_else(|| panic!("the requested Rust file was not written: {outcome:?}"));
    let arguments: serde_json::Value =
        serde_json::from_str(&target.arguments).expect("write arguments are JSON");
    let source = arguments["content"].as_str().expect("written source bytes");

    assert_eq!(
        source,
        "pub fn millimetres_to_metres(value: f64) -> f64 {\n    value / 1000.0\n}\n"
    );
    assert!(
        outcome.steps.iter().any(|step| {
            step.tool == "run_command"
                && step.arguments.contains("cat src/si_units.rs")
                && step.result == source
        }),
        "verification must observe the generated bytes: {outcome:?}"
    );
}

#[test]
fn rust_constant_request_writes_source_and_observes_it() {
    assert_generated_source(
        "Create a new file src/ladder_probe.rs in this repository containing a single public \
         Rust constant LADDER_PROBE of type &str with the value probe.",
        "src/ladder_probe.rs",
        "pub const LADDER_PROBE: &str = \"probe\";\n",
    );
}

#[test]
fn rust_test_request_writes_source_and_observes_it() {
    assert_generated_source(
        "Create a new file tests/unit/ladder_probe.rs in this repository containing a single \
         Rust test named ladder_probe_runs that asserts 1 equals 1.",
        "tests/unit/ladder_probe.rs",
        "#[test]\nfn ladder_probe_runs() {\n    assert_eq!(1, 1);\n}\n",
    );
}

#[test]
fn rust_addition_test_preserves_the_requested_expression() {
    assert_generated_source(
        "Create a Rust test file tests/integration/ladder_probe.rs in this repository containing \
         one Rust test named ladder_integration_probe asserting 2 plus 2 equals 4.",
        "tests/integration/ladder_probe.rs",
        "#[test]\nfn ladder_integration_probe() {\n    assert_eq!(2 + 2, 4);\n}\n",
    );
}

#[test]
fn multilingual_rust_function_requests_generate_source() {
    for (task, path, name) in [
        (
            "Создай файл src/ladder_ru.rs с одной публичной функцией на Rust с именем \
             ladder_ru, которая возвращает число 1.",
            "src/ladder_ru.rs",
            "ladder_ru",
        ),
        (
            "在这个仓库中创建文件 src/ladder_zh.rs，其中包含一个名为 ladder_zh 的公共 Rust \
             函数，返回数字 1。",
            "src/ladder_zh.rs",
            "ladder_zh",
        ),
        (
            "इस रिपॉजिटरी में src/ladder_hi.rs फ़ाइल बनाएँ जिसमें ladder_hi नाम का एक सार्वजनिक \
             Rust फ़ंक्शन हो जो 1 लौटाता है।",
            "src/ladder_hi.rs",
            "ladder_hi",
        ),
    ] {
        assert_generated_source(
            task,
            path,
            &format!("pub fn {name}() -> i64 {{\n    1\n}}\n"),
        );
    }
}

#[test]
fn coding_source_templates_and_outcomes_are_seed_grounded() {
    for intent in [
        "coding_source_function_division",
        "coding_source_function_return",
        "coding_source_string_constant",
        "coding_source_equality_test",
        "coding_source_binary_operation_test",
    ] {
        assert!(
            formal_ai::seed::response_for(intent, "rust").is_some(),
            "missing Rust template {intent}"
        );
    }
    for intent in [
        "coding_workspace_effect_observed",
        "coding_workspace_written_unverified",
        "coding_workspace_verification_failed",
    ] {
        for language in ["en", "ru", "hi", "zh"] {
            assert!(
                formal_ai::seed::response_for(intent, language).is_some(),
                "missing {language} response for {intent}"
            );
        }
    }

    let outcome = run_agentic_task(
        "Создай файл src/ladder_ru.rs с одной публичной функцией на Rust с именем \
         ladder_ru, которая возвращает число 1.",
    )
    .expect("isolated agent workspace");
    assert!(
        outcome.final_answer.starts_with("Файл `src/ladder_ru.rs`"),
        "Russian task must naturalize the seeded Russian outcome: {}",
        outcome.final_answer
    );
}

#[test]
fn repository_searches_use_the_named_code_subject() {
    for (task, expected) in [
        (
            "In this repository, find where the string example.org is emitted as evidence and \
             tell me the file name.",
            "example.org",
        ),
        (
            "In this repository, find where the function stable_id is defined and tell me the \
             file name.",
            "stable_id",
        ),
        (
            "In this repository, find where the function dialog_id is defined and tell me the \
             file name.",
            "dialog_id",
        ),
        (
            "In this repository, find where the excluded_folders array is defined and tell me \
             the file name.",
            "excluded_folders",
        ),
        (
            "In this repository, find where reciprocalRankFusion is implemented in JavaScript \
             and tell me the file name.",
            "reciprocalRankFusion",
        ),
        (
            "In this repository, find where the Context struct for world models is defined and \
             tell me the file name.",
            "Context",
        ),
        (
            "In this repository, find where the summarize function is defined and tell me the \
             file name.",
            "summarize",
        ),
    ] {
        let AgenticPlan::ToolCalls(calls) =
            plan_chat_step(&[ChatMessage::user(task)], &["grep"]).expect("grep plan")
        else {
            panic!("repository search must call grep: {task}");
        };
        assert_eq!(calls.len(), 1, "one focused grep: {task}");
        let arguments: serde_json::Value =
            serde_json::from_str(&calls[0].arguments).expect("grep arguments");
        assert_eq!(arguments["query"], expected, "focused query: {task}");
        assert_eq!(arguments["pattern"], expected, "focused pattern: {task}");
    }
}

#[test]
fn collection_edit_reads_transforms_writes_and_observes_workspace_bytes() {
    const TASK: &str = "In this repository, in scripts/detect-code-changes.rs, add \
        \"dev/log/\" to the excluded_folders array.";
    const BEFORE: &str = "fn is_excluded(file_path: &str) -> bool {\n    \
        let excluded_folders = [\"changelog.d/\", \"docs/\", \"examples/\"];\n    \
        excluded_folders.iter().any(|folder| file_path.starts_with(folder))\n}\n";
    const AFTER: &str = "fn is_excluded(file_path: &str) -> bool {\n    \
        let excluded_folders = [\"changelog.d/\", \"docs/\", \"examples/\", \"dev/log/\"];\n    \
        excluded_folders.iter().any(|folder| file_path.starts_with(folder))\n}\n";
    let tools = ["read_file", "write_file", "run_command"];
    let mut messages = vec![ChatMessage::user(TASK)];

    let read = only_call(plan_chat_step(&messages, &tools));
    assert_eq!(read.tool, "read_file");
    assert_eq!(
        json_arguments(&read.arguments)["path"],
        "scripts/detect-code-changes.rs"
    );
    push_result(&mut messages, "read_1", &read, BEFORE);

    let write = only_call(plan_chat_step(&messages, &tools));
    assert_eq!(write.tool, "write_file");
    let arguments = json_arguments(&write.arguments);
    assert_eq!(arguments["path"], "scripts/detect-code-changes.rs");
    assert_eq!(arguments["content"], AFTER);
    push_result(&mut messages, "write_1", &write, "updated");

    let verify = only_call(plan_chat_step(&messages, &tools));
    assert_eq!(verify.tool, "run_command");
    assert_eq!(
        json_arguments(&verify.arguments)["command"],
        "cat scripts/detect-code-changes.rs"
    );
    push_result(&mut messages, "run_1", &verify, AFTER);

    let Some(AgenticPlan::Final(answer)) = plan_chat_step(&messages, &tools) else {
        panic!("an observed edit must finish");
    };
    assert!(answer.contains("observed"), "{answer}");
}

#[test]
fn compiler_measurement_and_same_task_authorship_are_preserved() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let read = |path: &str| {
        std::fs::read_to_string(root.join(path)).unwrap_or_else(|error| panic!("{path}: {error}"))
    };
    let runner = read("experiments/issue_847_coding_ladder/run_coding_ladder.sh");
    assert!(runner.contains("[\"rustc\", \"--edition=2021\""));
    assert!(runner.contains("rust_target_existed[created]"));
    assert!(runner.contains("\"dataset_total\": len(all_tasks)"));
    assert!(runner.contains("\"complete\": not only"));
    assert!(runner.contains("results-partial-$FILTER_SLUG.json"));
    assert!(runner.contains("expect_from_file"));
    assert!(runner.contains("re.MULTILINE"));

    let prompts: serde_json::Value =
        serde_json::from_str(&read("experiments/issue_847_coding_ladder/prompts.json"))
            .expect("coding ladder prompts are JSON");
    for id in ["read.read_version", "lang.zh_read"] {
        let task = prompts["tasks"]
            .as_array()
            .expect("task array")
            .iter()
            .find(|task| task["id"] == id)
            .unwrap_or_else(|| panic!("missing task {id}"));
        assert_eq!(task["expect_from_file"]["path"], "Cargo.toml");
        assert!(
            task.get("expect_answer").is_none(),
            "{id} must not pin a release number"
        );
    }

    let invariant = read(
        "docs/case-studies/issue-848/self-hosting-authorship/coding-task-execution-invariant.lino",
    );
    assert_eq!(
        invariant,
        concat!(
            "coding_task_execution_contract\n",
            "  record_type meta_invariant\n",
            "  source_generation \"render executable source from the formalized request, never ",
            "echo request prose\"\n",
            "  verification \"compile or inspect the exact bytes written to the requested ",
            "workspace target\"\n",
            "  scoring \"record success only after an observed_workspace_effect passes its ",
            "task verifier\"",
        )
    );

    let session = "ses_04160c59fffe3FDUKteR56kfQp";
    let agent_log = read("docs/case-studies/issue-848/self-hosting-authorship/agent-cli.log");
    assert!(agent_log.contains(session));
    let formal_ai_log = read("docs/case-studies/issue-848/self-hosting-authorship/formal-ai.log");
    for transition in [
        "planned ToolCalls",
        "tool=write",
        "tool: \"bash\"",
        "planned Final",
        "coding-task-execution-invariant.lino",
    ] {
        assert!(
            formal_ai_log.contains(transition),
            "server trace is missing {transition}"
        );
    }

    let decomposition =
        read("docs/case-studies/issue-848/self-hosting-authorship/decomposition.lino");
    assert_eq!(decomposition.matches("issue_848_smallest_leaf_").count(), 4);
    assert_eq!(
        decomposition
            .matches("authorship formal_ai_agent_cli")
            .count(),
        1
    );
    assert!(decomposition.contains(&format!("session {session}")));
    assert!(decomposition.contains("formal_ai_authored_percent 25"));
}

#[test]
fn case_study_and_release_trace_every_issue_848_acceptance_boundary() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let read = |path: &str| {
        std::fs::read_to_string(root.join(path)).unwrap_or_else(|error| panic!("{path}: {error}"))
    };
    let case_study = read("docs/case-studies/issue-848/README.md");
    for evidence in [
        "38/130",
        "61/130",
        "62/130",
        "compiler-valid",
        "test_authoring",
        "targeted_edit",
        "multilingual",
        "ses_04160c59fffe3FDUKteR56kfQp",
    ] {
        assert!(case_study.contains(evidence), "missing {evidence}");
    }

    let traceability = read("docs/case-studies/issue-848/requirements.md");
    for index in 1..=8 {
        assert!(
            traceability.contains(&format!("R848-{index}")),
            "missing R848-{index}"
        );
    }
    let global = read("REQUIREMENTS.md");
    assert!(global.contains("## Issue #848"));
    assert!(global.contains("R848-8"));

    let fragment = read("changelog.d/20260801_848_coding_tasks.md");
    assert!(fragment.contains("bump: minor"));
    assert!(fragment.contains("#848"));
}

fn assert_generated_source(task: &str, path: &str, expected: &str) {
    let outcome = run_agentic_task(task).expect("isolated agent workspace");
    assert!(
        !outcome.hit_turn_cap,
        "agent loop must terminate: {outcome:?}"
    );

    let write = outcome
        .steps
        .iter()
        .find(|step| {
            step.tool == "write_file"
                && serde_json::from_str::<serde_json::Value>(&step.arguments)
                    .ok()
                    .and_then(|arguments| arguments["path"].as_str().map(str::to_owned))
                    .is_some_and(|written| written == path)
        })
        .unwrap_or_else(|| panic!("requested file was not written: {outcome:?}"));
    let arguments: serde_json::Value =
        serde_json::from_str(&write.arguments).expect("write arguments are JSON");
    assert_eq!(arguments["content"], expected, "generated source: {task}");
    assert!(
        outcome.steps.iter().any(|step| {
            step.tool == "run_command"
                && step.arguments.contains(&format!("cat {path}"))
                && step.result == expected
        }),
        "verification must observe the generated bytes: {outcome:?}"
    );
}

#[track_caller]
fn only_call(plan: Option<AgenticPlan>) -> formal_ai::agentic_coding::PlannedToolCall {
    match plan {
        Some(AgenticPlan::ToolCalls(mut calls)) => {
            assert_eq!(calls.len(), 1);
            calls.remove(0)
        }
        other => panic!("expected one tool call, got {other:?}"),
    }
}

fn json_arguments(arguments: &str) -> serde_json::Value {
    serde_json::from_str(arguments).expect("tool arguments are JSON")
}

fn push_result(
    messages: &mut Vec<ChatMessage>,
    id: &str,
    call: &formal_ai::agentic_coding::PlannedToolCall,
    result: &str,
) {
    messages.push(ChatMessage::assistant_tool_calls(vec![ToolCall::function(
        id.to_owned(),
        call.tool.clone(),
        call.arguments.clone(),
    )]));
    messages.push(ChatMessage::tool_result(
        id.to_owned(),
        call.tool.clone(),
        result.to_owned(),
    ));
}
